package com.quicksilver.mwo.mechbay.mechlab;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Trevin
 */
public class MechTreeDialogBox extends JDialog {
    private static final long serialVersionUID = 5706542986933801709L;
    
    JButton closeButton;
    private JPanel BasicPanel;
    private JPanel ButtonPanel;
    private JPanel ElitePanel;
    private JPanel MasterPanel;
    private JLabel anchorTurnLabel;
    private JLabel armReflexLabel;
    private JLabel coolrunLabel;
    private JLabel fastFireLabel;
    private JLabel hardBrakeLabel;
    private JLabel heatContainmentLabel;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private JLabel kineticBurstLabel;
    private JLabel pinpointLabel;
    private JLabel pinpointLabel1;
    private JLabel quickIgnitionLabel;
    private JLabel speedTweakLabel;
    private JLabel twistSpeedLabel;
    private JLabel twistXLabel;
    private JLabel xpLabel1;
    private JLabel xpLabel10;
    private JLabel xpLabel11;
    private JLabel xpLabel12;
    private JLabel xpLabel13;
    private JLabel xpLabel2;
    private JLabel xpLabel3;
    private JLabel xpLabel4;
    private JLabel xpLabel5;
    private JLabel xpLabel6;
    private JLabel xpLabel7;
    private JLabel xpLabel8;
    private JLabel xpLabel9;

    public MechTreeDialogBox(Frame paramFrame, boolean paramBoolean) {
        super(paramFrame, paramBoolean);
        initComponents();
        setResizable(false);
    }

    private void initComponents() {
        this.BasicPanel = new JPanel();
        this.xpLabel1 = new JLabel();
        this.twistXLabel = new JLabel();
        this.xpLabel2 = new JLabel();
        this.anchorTurnLabel = new JLabel();
        this.xpLabel3 = new JLabel();
        this.hardBrakeLabel = new JLabel();
        this.xpLabel4 = new JLabel();
        this.kineticBurstLabel = new JLabel();
        this.xpLabel5 = new JLabel();
        this.twistSpeedLabel = new JLabel();
        this.xpLabel6 = new JLabel();
        this.armReflexLabel = new JLabel();
        this.xpLabel7 = new JLabel();
        this.coolrunLabel = new JLabel();
        this.xpLabel8 = new JLabel();
        this.heatContainmentLabel = new JLabel();
        this.ElitePanel = new JPanel();
        this.xpLabel9 = new JLabel();
        this.pinpointLabel = new JLabel();
        this.xpLabel10 = new JLabel();
        this.speedTweakLabel = new JLabel();
        this.xpLabel11 = new JLabel();
        this.fastFireLabel = new JLabel();
        this.xpLabel12 = new JLabel();
        this.quickIgnitionLabel = new JLabel();
        this.MasterPanel = new JPanel();
        this.xpLabel13 = new JLabel();
        this.pinpointLabel1 = new JLabel();
        this.jScrollPane1 = new JScrollPane();
        this.jTextArea1 = new JTextArea();
        this.ButtonPanel = new JPanel();
        this.closeButton = new JButton();
        setDefaultCloseOperation(2);
        setTitle("Mech Trees");
        setMinimumSize(new Dimension(700, 300));
        setName("MechTreeDialog");
        getContentPane().setLayout(new GridBagLayout());
        this.BasicPanel.setBackground(new Color(64, 128, 255));
        this.BasicPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Basic", 2, 2, new Font("Moire", 0, 11)));
        this.BasicPanel.setOpaque(false);
        this.BasicPanel.setLayout(new GridBagLayout());
        this.xpLabel1.setBackground(new Color(64, 128, 255));
        this.xpLabel1.setFont(new Font("Moire", 0, 10));
        this.xpLabel1.setHorizontalAlignment(0);
        this.xpLabel1.setText("2500");
        this.xpLabel1.setAlignmentY(0.0F);
        this.xpLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        GridBagConstraints localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 6;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel1, localGridBagConstraints);
        this.twistXLabel.setBackground(new Color(64, 128, 255));
        this.twistXLabel.setFont(new Font("Moire", 0, 10));
        this.twistXLabel.setHorizontalAlignment(0);
        this.twistXLabel.setText("Torso Twist Range +10.0%");
        this.twistXLabel.setAlignmentY(0.0F);
        this.twistXLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Twist X", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 7;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.twistXLabel, localGridBagConstraints);
        this.xpLabel2.setBackground(new Color(64, 128, 255));
        this.xpLabel2.setFont(new Font("Moire", 0, 10));
        this.xpLabel2.setHorizontalAlignment(0);
        this.xpLabel2.setText("3500");
        this.xpLabel2.setAlignmentY(0.0F);
        this.xpLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 9;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel2, localGridBagConstraints);
        this.anchorTurnLabel.setBackground(new Color(64, 128, 255));
        this.anchorTurnLabel.setFont(new Font("Moire", 0, 10));
        this.anchorTurnLabel.setHorizontalAlignment(0);
        this.anchorTurnLabel.setText("Turning Speed +10.0%");
        this.anchorTurnLabel.setAlignmentY(0.0F);
        this.anchorTurnLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Anchor Turn", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 10;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.anchorTurnLabel, localGridBagConstraints);
        this.xpLabel3.setBackground(new Color(64, 128, 255));
        this.xpLabel3.setFont(new Font("Moire", 0, 10));
        this.xpLabel3.setHorizontalAlignment(0);
        this.xpLabel3.setText("1500");
        this.xpLabel3.setAlignmentY(0.0F);
        this.xpLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel3, localGridBagConstraints);
        this.hardBrakeLabel.setBackground(new Color(64, 128, 255));
        this.hardBrakeLabel.setFont(new Font("Moire", 0, 10));
        this.hardBrakeLabel.setHorizontalAlignment(0);
        this.hardBrakeLabel.setText("Decceleration +25%");
        this.hardBrakeLabel.setAlignmentY(0.0F);
        this.hardBrakeLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Hard Brake", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.hardBrakeLabel, localGridBagConstraints);
        this.xpLabel4.setBackground(new Color(64, 128, 255));
        this.xpLabel4.setFont(new Font("Moire", 0, 10));
        this.xpLabel4.setHorizontalAlignment(0);
        this.xpLabel4.setText("1000");
        this.xpLabel4.setAlignmentY(0.0F);
        this.xpLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel4, localGridBagConstraints);
        this.kineticBurstLabel.setBackground(new Color(64, 128, 255));
        this.kineticBurstLabel.setFont(new Font("Moire", 0, 10));
        this.kineticBurstLabel.setHorizontalAlignment(0);
        this.kineticBurstLabel.setText("Acceleration +22.5%");
        this.kineticBurstLabel.setAlignmentY(0.0F);
        this.kineticBurstLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Kinetic Burst", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 4;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.kineticBurstLabel, localGridBagConstraints);
        this.xpLabel5.setBackground(new Color(64, 128, 255));
        this.xpLabel5.setFont(new Font("Moire", 0, 10));
        this.xpLabel5.setHorizontalAlignment(0);
        this.xpLabel5.setText("1500");
        this.xpLabel5.setAlignmentY(0.0F);
        this.xpLabel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel5, localGridBagConstraints);
        this.twistSpeedLabel.setBackground(new Color(64, 128, 255));
        this.twistSpeedLabel.setFont(new Font("Moire", 0, 10));
        this.twistSpeedLabel.setHorizontalAlignment(0);
        this.twistSpeedLabel.setText("Twist Speed +15.0%");
        this.twistSpeedLabel.setAlignmentY(0.0F);
        this.twistSpeedLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Twist Speed", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 4;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.twistSpeedLabel, localGridBagConstraints);
        this.xpLabel6.setBackground(new Color(64, 128, 255));
        this.xpLabel6.setFont(new Font("Moire", 0, 10));
        this.xpLabel6.setHorizontalAlignment(0);
        this.xpLabel6.setText("2500");
        this.xpLabel6.setAlignmentY(0.0F);
        this.xpLabel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 6;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel6, localGridBagConstraints);
        this.armReflexLabel.setBackground(new Color(64, 128, 255));
        this.armReflexLabel.setFont(new Font("Moire", 0, 10));
        this.armReflexLabel.setHorizontalAlignment(0);
        this.armReflexLabel.setText("Arm Speed +20.0%");
        this.armReflexLabel.setAlignmentY(0.0F);
        this.armReflexLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Arm Reflex", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 7;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.armReflexLabel, localGridBagConstraints);
        this.xpLabel7.setBackground(new Color(64, 128, 255));
        this.xpLabel7.setFont(new Font("Moire", 0, 10));
        this.xpLabel7.setHorizontalAlignment(0);
        this.xpLabel7.setText("750");
        this.xpLabel7.setAlignmentY(0.0F);
        this.xpLabel7.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel7, localGridBagConstraints);
        this.coolrunLabel.setBackground(new Color(64, 128, 255));
        this.coolrunLabel.setFont(new Font("Moire", 0, 10));
        this.coolrunLabel.setHorizontalAlignment(0);
        this.coolrunLabel.setText("Heat Dissipation +7.5%");
        this.coolrunLabel.setAlignmentY(0.0F);
        this.coolrunLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cool Run", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.coolrunLabel, localGridBagConstraints);
        this.xpLabel8.setBackground(new Color(64, 128, 255));
        this.xpLabel8.setFont(new Font("Moire", 0, 10));
        this.xpLabel8.setHorizontalAlignment(0);
        this.xpLabel8.setText("1000");
        this.xpLabel8.setAlignmentY(0.0F);
        this.xpLabel8.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 9;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.xpLabel8, localGridBagConstraints);
        this.heatContainmentLabel.setBackground(new Color(64, 128, 255));
        this.heatContainmentLabel.setFont(new Font("Moire", 0, 10));
        this.heatContainmentLabel.setHorizontalAlignment(0);
        this.heatContainmentLabel.setText("Heat Threshold +10.0%");
        this.heatContainmentLabel.setAlignmentY(0.0F);
        this.heatContainmentLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Heat Containment", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 10;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.BasicPanel.add(this.heatContainmentLabel, localGridBagConstraints);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 5;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.BasicPanel, localGridBagConstraints);
        this.ElitePanel.setBackground(new Color(64, 255, 64));
        this.ElitePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Elite", 2, 2, new Font("Moire", 0, 11)));
        this.ElitePanel.setOpaque(false);
        this.ElitePanel.setLayout(new GridBagLayout());
        this.xpLabel9.setBackground(new Color(64, 255, 64));
        this.xpLabel9.setFont(new Font("Moire", 0, 10));
        this.xpLabel9.setHorizontalAlignment(0);
        this.xpLabel9.setText("3000");
        this.xpLabel9.setAlignmentY(0.0F);
        this.xpLabel9.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.xpLabel9, localGridBagConstraints);
        this.pinpointLabel.setBackground(new Color(64, 255, 64));
        this.pinpointLabel.setFont(new Font("Moire", 0, 10));
        this.pinpointLabel.setHorizontalAlignment(0);
        this.pinpointLabel.setText("Weapon Convergence +15.0%");
        this.pinpointLabel.setAlignmentY(0.0F);
        this.pinpointLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Pinpoint", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 4;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.pinpointLabel, localGridBagConstraints);
        this.xpLabel10.setBackground(new Color(64, 255, 64));
        this.xpLabel10.setFont(new Font("Moire", 0, 10));
        this.xpLabel10.setHorizontalAlignment(0);
        this.xpLabel10.setText("8500");
        this.xpLabel10.setAlignmentY(0.0F);
        this.xpLabel10.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.xpLabel10, localGridBagConstraints);
        this.speedTweakLabel.setBackground(new Color(64, 255, 64));
        this.speedTweakLabel.setFont(new Font("Moire", 0, 10));
        this.speedTweakLabel.setHorizontalAlignment(0);
        this.speedTweakLabel.setText("Top Speed +10%");
        this.speedTweakLabel.setAlignmentY(0.0F);
        this.speedTweakLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Speed Tweak", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 4;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.speedTweakLabel, localGridBagConstraints);
        this.xpLabel11.setBackground(new Color(64, 255, 64));
        this.xpLabel11.setFont(new Font("Moire", 0, 10));
        this.xpLabel11.setHorizontalAlignment(0);
        this.xpLabel11.setText("6000");
        this.xpLabel11.setAlignmentY(0.0F);
        this.xpLabel11.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.xpLabel11, localGridBagConstraints);
        this.fastFireLabel.setBackground(new Color(64, 255, 64));
        this.fastFireLabel.setFont(new Font("Moire", 0, 10));
        this.fastFireLabel.setHorizontalAlignment(0);
        this.fastFireLabel.setText("Weapon Cooldown -5.0%");
        this.fastFireLabel.setAlignmentY(0.0F);
        this.fastFireLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Fast Fire", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.fastFireLabel, localGridBagConstraints);
        this.xpLabel12.setBackground(new Color(64, 255, 64));
        this.xpLabel12.setFont(new Font("Moire", 0, 10));
        this.xpLabel12.setHorizontalAlignment(0);
        this.xpLabel12.setText("4000");
        this.xpLabel12.setAlignmentY(0.0F);
        this.xpLabel12.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.xpLabel12, localGridBagConstraints);
        this.quickIgnitionLabel.setBackground(new Color(64, 255, 64));
        this.quickIgnitionLabel.setFont(new Font("Moire", 0, 10));
        this.quickIgnitionLabel.setHorizontalAlignment(0);
        this.quickIgnitionLabel.setText("Start/Shutdown Speed +33%");
        this.quickIgnitionLabel.setAlignmentY(0.0F);
        this.quickIgnitionLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Quick Ignition", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ElitePanel.add(this.quickIgnitionLabel, localGridBagConstraints);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridwidth = 3;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.ElitePanel, localGridBagConstraints);
        this.MasterPanel.setBackground(new Color(255, 255, 64));
        this.MasterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Master", 2, 2, new Font("Moire", 0, 11)));
        this.MasterPanel.setOpaque(false);
        this.MasterPanel.setLayout(new GridBagLayout());
        this.xpLabel13.setBackground(new Color(255, 255, 64));
        this.xpLabel13.setFont(new Font("Moire", 0, 10));
        this.xpLabel13.setHorizontalAlignment(0);
        this.xpLabel13.setText("21500");
        this.xpLabel13.setAlignmentY(0.0F);
        this.xpLabel13.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.MasterPanel.add(this.xpLabel13, localGridBagConstraints);
        this.pinpointLabel1.setBackground(new Color(255, 255, 64));
        this.pinpointLabel1.setFont(new Font("Moire", 0, 10));
        this.pinpointLabel1.setHorizontalAlignment(0);
        this.pinpointLabel1.setText("1 Additional Module");
        this.pinpointLabel1.setAlignmentY(0.0F);
        this.pinpointLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Module Slot", 2, 2, new Font("Moire", 0, 11)));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.gridwidth = 2;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.MasterPanel.add(this.pinpointLabel1, localGridBagConstraints);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.MasterPanel, localGridBagConstraints);
        this.jTextArea1.setColumns(20);
        this.jTextArea1.setFont(new Font("Moire", 0, 11));
        this.jTextArea1.setLineWrap(true);
        this.jTextArea1.setRows(5);
        this.jTextArea1.setText("*Elite requires 3 variants to have all 8        Basic upgrades.\n\n*Master requires 3 variants in the same   weight class to have Elite status.\n\n*Getting all Elite upgrades, doubles all Basic upgrades effects.");
        this.jTextArea1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Notes", 2, 2, new Font("Moire", 0, 11)));
        this.jScrollPane1.setViewportView(this.jTextArea1);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        localGridBagConstraints.gridheight = 3;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.jScrollPane1, localGridBagConstraints);
        this.ButtonPanel.setLayout(new GridBagLayout());
        this.closeButton.setFont(new Font("Moire", 0, 12));
        this.closeButton.setText("Close");
        this.closeButton.setMaximumSize(new Dimension(120, 30));
        this.closeButton.setMinimumSize(new Dimension(120, 30));
        this.closeButton.setPreferredSize(new Dimension(110, 30));
        this.closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent paramAnonymousActionEvent) {
                MechTreeDialogBox.this.closeButtonActionPerformed(paramAnonymousActionEvent);
            }
        });
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.ButtonPanel.add(this.closeButton, localGridBagConstraints);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 2;
        localGridBagConstraints.fill = 1;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.ButtonPanel, localGridBagConstraints);
        pack();
    }

    private void closeButtonActionPerformed(ActionEvent paramActionEvent) {
        dispose();
    }
}