package com.quicksilver.mwo.mechbay.mechlab;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

public class PilotTreeDialogBox extends JDialog {
    private static final long serialVersionUID = -6498185444889999733L;
    
    JButton closeButton;
    private JPanel ButtonPanel;
    private JTabbedPane PilotTreeTabbedPane;
    private JPanel SensorTreePanel;
    private JPanel SupportTreePanel;
    private JPanel TargetingTreePanel;
    private JPanel TargetingTreePanel1;
    private JPanel VisionTreePanel;
    private JLabel advZoomLabel;
    private JLabel hideDamageLabel;
    private JLabel hideDamageLabel1;
    private JLabel hideDamageLabel2;
    private JLabel hideDamageLabel3;
    private JLabel infoGatherLabel;
    private JLabel infoGatherLabel1;
    private JLabel infoGatherLabel2;
    private JLabel infoGatherLabel3;
    private JLabel magnetometerLabel;
    private JLabel magnetometerLabel1;
    private JLabel magnetometerLabel2;
    private JLabel magnetometerLabel3;
    private JLabel modeEnhanceLabel;
    private JLabel orbitalScanLabel;
    private JLabel orbitalScanLabel1;
    private JLabel orbitalScanLabel2;
    private JLabel orbitalScanLabel3;
    private JLabel seismicLabel;
    private JLabel seismicLabel1;
    private JLabel seismicLabel2;
    private JLabel seismicLabel3;
    private JLabel seismicLabel4;
    private JLabel sensorRangeLabel;
    private JLabel sensorRangeLabel1;
    private JLabel sensorRangeLabel2;
    private JLabel sensorRangeLabel3;
    private JLabel sensorRangeLabel4;
    private JLabel signalLossLabel;
    private JLabel signalLossLabel1;
    private JLabel signalLossLabel2;
    private JLabel signalLossLabel3;
    private JLabel xpLabel1;
    private JLabel xpLabel10;
    private JLabel xpLabel11;
    private JLabel xpLabel12;
    private JLabel xpLabel13;
    private JLabel xpLabel14;
    private JLabel xpLabel15;
    private JLabel xpLabel16;
    private JLabel xpLabel17;
    private JLabel xpLabel18;
    private JLabel xpLabel19;
    private JLabel xpLabel2;
    private JLabel xpLabel20;
    private JLabel xpLabel21;
    private JLabel xpLabel22;
    private JLabel xpLabel23;
    private JLabel xpLabel24;
    private JLabel xpLabel25;
    private JLabel xpLabel26;
    private JLabel xpLabel27;
    private JLabel xpLabel28;
    private JLabel xpLabel29;
    private JLabel xpLabel3;
    private JLabel xpLabel31;
    private JLabel xpLabel32;
    private JLabel xpLabel33;
    private JLabel xpLabel35;
    private JLabel xpLabel4;
    private JLabel xpLabel5;
    private JLabel xpLabel6;
    private JLabel xpLabel7;
    private JLabel xpLabel8;
    private JLabel xpLabel9;
    private JLabel zoomDisruptorLabel;

    public PilotTreeDialogBox(Frame paramFrame, boolean paramBoolean) {
        super(paramFrame, paramBoolean);
        initComponents();
        setResizable(false);
    }

    private void initComponents() {
        this.PilotTreeTabbedPane = new JTabbedPane();
        this.VisionTreePanel = new JPanel();
        this.xpLabel1 = new JLabel();
        this.advZoomLabel = new JLabel();
        this.xpLabel2 = new JLabel();
        this.zoomDisruptorLabel = new JLabel();
        this.xpLabel3 = new JLabel();
        this.modeEnhanceLabel = new JLabel();
        this.SensorTreePanel = new JPanel();
        this.xpLabel4 = new JLabel();
        this.infoGatherLabel = new JLabel();
        this.xpLabel5 = new JLabel();
        this.hideDamageLabel = new JLabel();
        this.xpLabel6 = new JLabel();
        this.signalLossLabel = new JLabel();
        this.xpLabel7 = new JLabel();
        this.sensorRangeLabel = new JLabel();
        this.xpLabel8 = new JLabel();
        this.seismicLabel = new JLabel();
        this.xpLabel9 = new JLabel();
        this.orbitalScanLabel = new JLabel();
        this.xpLabel10 = new JLabel();
        this.magnetometerLabel = new JLabel();
        this.seismicLabel3 = new JLabel();
        this.xpLabel28 = new JLabel();
        this.sensorRangeLabel4 = new JLabel();
        this.xpLabel29 = new JLabel();
        this.SupportTreePanel = new JPanel();
        this.xpLabel11 = new JLabel();
        this.infoGatherLabel1 = new JLabel();
        this.xpLabel12 = new JLabel();
        this.hideDamageLabel1 = new JLabel();
        this.xpLabel13 = new JLabel();
        this.signalLossLabel1 = new JLabel();
        this.xpLabel14 = new JLabel();
        this.sensorRangeLabel1 = new JLabel();
        this.xpLabel15 = new JLabel();
        this.seismicLabel1 = new JLabel();
        this.xpLabel16 = new JLabel();
        this.orbitalScanLabel1 = new JLabel();
        this.xpLabel17 = new JLabel();
        this.magnetometerLabel1 = new JLabel();
        this.magnetometerLabel3 = new JLabel();
        this.xpLabel27 = new JLabel();
        this.TargetingTreePanel = new JPanel();
        this.xpLabel18 = new JLabel();
        this.infoGatherLabel2 = new JLabel();
        this.xpLabel19 = new JLabel();
        this.hideDamageLabel2 = new JLabel();
        this.xpLabel20 = new JLabel();
        this.signalLossLabel2 = new JLabel();
        this.xpLabel21 = new JLabel();
        this.sensorRangeLabel2 = new JLabel();
        this.xpLabel22 = new JLabel();
        this.seismicLabel2 = new JLabel();
        this.xpLabel23 = new JLabel();
        this.orbitalScanLabel2 = new JLabel();
        this.xpLabel24 = new JLabel();
        this.magnetometerLabel2 = new JLabel();
        this.xpLabel25 = new JLabel();
        this.infoGatherLabel3 = new JLabel();
        this.sensorRangeLabel3 = new JLabel();
        this.xpLabel26 = new JLabel();
        this.TargetingTreePanel1 = new JPanel();
        this.xpLabel31 = new JLabel();
        this.hideDamageLabel3 = new JLabel();
        this.xpLabel32 = new JLabel();
        this.signalLossLabel3 = new JLabel();
        this.xpLabel33 = new JLabel();
        this.seismicLabel4 = new JLabel();
        this.xpLabel35 = new JLabel();
        this.orbitalScanLabel3 = new JLabel();
        this.ButtonPanel = new JPanel();
        this.closeButton = new JButton();
        setDefaultCloseOperation(2);
        setTitle("Pilot Trees");
        setMinimumSize(new Dimension(650, 350));
        setName("PilotTreeDialog");
        getContentPane().setLayout(new GridBagLayout());
        this.PilotTreeTabbedPane.setAlignmentX(0.0F);
        this.PilotTreeTabbedPane.setAlignmentY(0.0F);
        this.PilotTreeTabbedPane.setFont(new Font("Moire", 0, 12));
        this.PilotTreeTabbedPane.setMaximumSize(new Dimension(520, 300));
        this.PilotTreeTabbedPane.setMinimumSize(new Dimension(520, 300));
        this.PilotTreeTabbedPane.setPreferredSize(new Dimension(520, 300));
        this.VisionTreePanel.setMaximumSize(new Dimension(132, 300));
        this.VisionTreePanel.setMinimumSize(new Dimension(132, 300));
        this.VisionTreePanel.setPreferredSize(new Dimension(132, 300));
        this.VisionTreePanel.setLayout(new GridBagLayout());
        this.xpLabel1.setFont(new Font("Moire", 0, 10));
        this.xpLabel1.setText("5000");
        this.xpLabel1.setAlignmentY(0.0F);
        this.xpLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel1.setMaximumSize(new Dimension(50, 38));
        this.xpLabel1.setMinimumSize(new Dimension(50, 38));
        this.xpLabel1.setPreferredSize(new Dimension(50, 38));
        GridBagConstraints localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        this.VisionTreePanel.add(this.xpLabel1, localGridBagConstraints);
        this.advZoomLabel.setFont(new Font("Moire", 0, 10));
        this.advZoomLabel.setText("PIP 4x Zoom");
        this.advZoomLabel.setAlignmentY(0.0F);
        this.advZoomLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Zoom", 0, 0, new Font("Moire", 0, 11)));
        this.advZoomLabel.setMaximumSize(new Dimension(200, 38));
        this.advZoomLabel.setMinimumSize(new Dimension(200, 38));
        this.advZoomLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        this.VisionTreePanel.add(this.advZoomLabel, localGridBagConstraints);
        this.xpLabel2.setFont(new Font("Moire", 0, 10));
        this.xpLabel2.setText("5000");
        this.xpLabel2.setAlignmentY(0.0F);
        this.xpLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel2.setEnabled(false);
        this.xpLabel2.setMaximumSize(new Dimension(50, 38));
        this.xpLabel2.setMinimumSize(new Dimension(50, 38));
        this.xpLabel2.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        this.VisionTreePanel.add(this.xpLabel2, localGridBagConstraints);
        this.zoomDisruptorLabel.setFont(new Font("Moire", 0, 10));
        this.zoomDisruptorLabel.setText("?");
        this.zoomDisruptorLabel.setAlignmentY(0.0F);
        this.zoomDisruptorLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Vision Mode Disruptor", 0, 0, new Font("Moire", 0, 11)));
        this.zoomDisruptorLabel.setEnabled(false);
        this.zoomDisruptorLabel.setMaximumSize(new Dimension(200, 38));
        this.zoomDisruptorLabel.setMinimumSize(new Dimension(200, 38));
        this.zoomDisruptorLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.VisionTreePanel.add(this.zoomDisruptorLabel, localGridBagConstraints);
        this.xpLabel3.setFont(new Font("Moire", 0, 10));
        this.xpLabel3.setText("5000");
        this.xpLabel3.setAlignmentY(0.0F);
        this.xpLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel3.setEnabled(false);
        this.xpLabel3.setMaximumSize(new Dimension(50, 38));
        this.xpLabel3.setMinimumSize(new Dimension(50, 38));
        this.xpLabel3.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 2;
        this.VisionTreePanel.add(this.xpLabel3, localGridBagConstraints);
        this.modeEnhanceLabel.setFont(new Font("Moire", 0, 10));
        this.modeEnhanceLabel.setText("?");
        this.modeEnhanceLabel.setAlignmentY(0.0F);
        this.modeEnhanceLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Vision Mode Enhancement", 0, 0, new Font("Moire", 0, 11)));
        this.modeEnhanceLabel.setEnabled(false);
        this.modeEnhanceLabel.setMaximumSize(new Dimension(200, 38));
        this.modeEnhanceLabel.setMinimumSize(new Dimension(200, 38));
        this.modeEnhanceLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        this.VisionTreePanel.add(this.modeEnhanceLabel, localGridBagConstraints);
        this.PilotTreeTabbedPane.addTab("Vision", this.VisionTreePanel);
        this.SensorTreePanel.setMaximumSize(new Dimension(132, 300));
        this.SensorTreePanel.setMinimumSize(new Dimension(132, 300));
        this.SensorTreePanel.setPreferredSize(new Dimension(132, 300));
        this.SensorTreePanel.setLayout(new GridBagLayout());
        this.xpLabel4.setFont(new Font("Moire", 0, 10));
        this.xpLabel4.setText("10000");
        this.xpLabel4.setAlignmentY(0.0F);
        this.xpLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel4.setMaximumSize(new Dimension(50, 38));
        this.xpLabel4.setMinimumSize(new Dimension(50, 38));
        this.xpLabel4.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        this.SensorTreePanel.add(this.xpLabel4, localGridBagConstraints);
        this.infoGatherLabel.setFont(new Font("Moire", 0, 10));
        this.infoGatherLabel.setText("Time for target info decreased 25%");
        this.infoGatherLabel.setAlignmentY(0.0F);
        this.infoGatherLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Target Info Gathering", 0, 0, new Font("Moire", 0, 11)));
        this.infoGatherLabel.setMaximumSize(new Dimension(200, 38));
        this.infoGatherLabel.setMinimumSize(new Dimension(200, 38));
        this.infoGatherLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.SensorTreePanel.add(this.infoGatherLabel, localGridBagConstraints);
        this.xpLabel5.setFont(new Font("Moire", 0, 10));
        this.xpLabel5.setText("5000");
        this.xpLabel5.setAlignmentY(0.0F);
        this.xpLabel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel5.setEnabled(false);
        this.xpLabel5.setMaximumSize(new Dimension(50, 38));
        this.xpLabel5.setMinimumSize(new Dimension(50, 38));
        this.xpLabel5.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 4;
        this.SensorTreePanel.add(this.xpLabel5, localGridBagConstraints);
        this.hideDamageLabel.setFont(new Font("Moire", 0, 10));
        this.hideDamageLabel.setText("?");
        this.hideDamageLabel.setAlignmentY(0.0F);
        this.hideDamageLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Hide Damage", 0, 0, new Font("Moire", 0, 11)));
        this.hideDamageLabel.setEnabled(false);
        this.hideDamageLabel.setMaximumSize(new Dimension(200, 38));
        this.hideDamageLabel.setMinimumSize(new Dimension(200, 38));
        this.hideDamageLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 4;
        this.SensorTreePanel.add(this.hideDamageLabel, localGridBagConstraints);
        this.xpLabel6.setFont(new Font("Moire", 0, 10));
        this.xpLabel6.setText("5000");
        this.xpLabel6.setAlignmentY(0.0F);
        this.xpLabel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel6.setMaximumSize(new Dimension(50, 38));
        this.xpLabel6.setMinimumSize(new Dimension(50, 38));
        this.xpLabel6.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 2;
        this.SensorTreePanel.add(this.xpLabel6, localGridBagConstraints);
        this.signalLossLabel.setFont(new Font("Moire", 0, 10));
        this.signalLossLabel.setText("?");
        this.signalLossLabel.setAlignmentY(0.0F);
        this.signalLossLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Target Deprivation", 0, 0, new Font("Moire", 0, 11)));
        this.signalLossLabel.setMaximumSize(new Dimension(200, 38));
        this.signalLossLabel.setMinimumSize(new Dimension(200, 38));
        this.signalLossLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        this.SensorTreePanel.add(this.signalLossLabel, localGridBagConstraints);
        this.xpLabel7.setFont(new Font("Moire", 0, 10));
        this.xpLabel7.setText("5000");
        this.xpLabel7.setAlignmentY(0.0F);
        this.xpLabel7.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel7.setEnabled(false);
        this.xpLabel7.setMaximumSize(new Dimension(50, 38));
        this.xpLabel7.setMinimumSize(new Dimension(50, 38));
        this.xpLabel7.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 3;
        this.SensorTreePanel.add(this.xpLabel7, localGridBagConstraints);
        this.sensorRangeLabel.setFont(new Font("Moire", 0, 10));
        this.sensorRangeLabel.setText("Increases sensor range by 15%");
        this.sensorRangeLabel.setAlignmentY(0.0F);
        this.sensorRangeLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Sensor Range", 0, 0, new Font("Moire", 0, 11)));
        this.sensorRangeLabel.setMaximumSize(new Dimension(200, 38));
        this.sensorRangeLabel.setMinimumSize(new Dimension(200, 38));
        this.sensorRangeLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        this.SensorTreePanel.add(this.sensorRangeLabel, localGridBagConstraints);
        this.xpLabel8.setFont(new Font("Moire", 0, 10));
        this.xpLabel8.setText("5000");
        this.xpLabel8.setAlignmentY(0.0F);
        this.xpLabel8.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel8.setMaximumSize(new Dimension(50, 38));
        this.xpLabel8.setMinimumSize(new Dimension(50, 38));
        this.xpLabel8.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        this.SensorTreePanel.add(this.xpLabel8, localGridBagConstraints);
        this.seismicLabel.setFont(new Font("Moire", 0, 10));
        this.seismicLabel.setText("?");
        this.seismicLabel.setAlignmentY(0.0F);
        this.seismicLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Seismic Sensor", 0, 0, new Font("Moire", 0, 11)));
        this.seismicLabel.setMaximumSize(new Dimension(200, 38));
        this.seismicLabel.setMinimumSize(new Dimension(200, 38));
        this.seismicLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 5;
        this.SensorTreePanel.add(this.seismicLabel, localGridBagConstraints);
        this.xpLabel9.setFont(new Font("Moire", 0, 10));
        this.xpLabel9.setText("5000");
        this.xpLabel9.setAlignmentY(0.0F);
        this.xpLabel9.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel9.setMaximumSize(new Dimension(50, 38));
        this.xpLabel9.setMinimumSize(new Dimension(50, 38));
        this.xpLabel9.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 5;
        this.SensorTreePanel.add(this.xpLabel9, localGridBagConstraints);
        this.orbitalScanLabel.setFont(new Font("Moire", 0, 10));
        this.orbitalScanLabel.setText("?");
        this.orbitalScanLabel.setAlignmentY(0.0F);
        this.orbitalScanLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Orbital Scan", 0, 0, new Font("Moire", 0, 11)));
        this.orbitalScanLabel.setEnabled(false);
        this.orbitalScanLabel.setMaximumSize(new Dimension(200, 38));
        this.orbitalScanLabel.setMinimumSize(new Dimension(200, 38));
        this.orbitalScanLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 3;
        this.SensorTreePanel.add(this.orbitalScanLabel, localGridBagConstraints);
        this.xpLabel10.setFont(new Font("Moire", 0, 10));
        this.xpLabel10.setText("5000");
        this.xpLabel10.setAlignmentY(0.0F);
        this.xpLabel10.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel10.setEnabled(false);
        this.xpLabel10.setMaximumSize(new Dimension(50, 38));
        this.xpLabel10.setMinimumSize(new Dimension(50, 38));
        this.xpLabel10.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 6;
        this.SensorTreePanel.add(this.xpLabel10, localGridBagConstraints);
        this.magnetometerLabel.setFont(new Font("Moire", 0, 10));
        this.magnetometerLabel.setText("?");
        this.magnetometerLabel.setAlignmentY(0.0F);
        this.magnetometerLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Magnetometer", 0, 0, new Font("Moire", 0, 11)));
        this.magnetometerLabel.setEnabled(false);
        this.magnetometerLabel.setMaximumSize(new Dimension(200, 38));
        this.magnetometerLabel.setMinimumSize(new Dimension(200, 38));
        this.magnetometerLabel.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 6;
        this.SensorTreePanel.add(this.magnetometerLabel, localGridBagConstraints);
        this.seismicLabel3.setFont(new Font("Moire", 0, 10));
        this.seismicLabel3.setText("?");
        this.seismicLabel3.setAlignmentY(0.0F);
        this.seismicLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Seismic Sensor", 0, 0, new Font("Moire", 0, 11)));
        this.seismicLabel3.setMaximumSize(new Dimension(200, 38));
        this.seismicLabel3.setMinimumSize(new Dimension(200, 38));
        this.seismicLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 5;
        this.SensorTreePanel.add(this.seismicLabel3, localGridBagConstraints);
        this.xpLabel28.setFont(new Font("Moire", 0, 10));
        this.xpLabel28.setText("7500");
        this.xpLabel28.setAlignmentY(0.0F);
        this.xpLabel28.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel28.setMaximumSize(new Dimension(50, 38));
        this.xpLabel28.setMinimumSize(new Dimension(50, 38));
        this.xpLabel28.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 5;
        this.SensorTreePanel.add(this.xpLabel28, localGridBagConstraints);
        this.sensorRangeLabel4.setFont(new Font("Moire", 0, 10));
        this.sensorRangeLabel4.setText("Increases sensor range by 25%");
        this.sensorRangeLabel4.setAlignmentY(0.0F);
        this.sensorRangeLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Sensor Range", 0, 0, new Font("Moire", 0, 11)));
        this.sensorRangeLabel4.setMaximumSize(new Dimension(200, 38));
        this.sensorRangeLabel4.setMinimumSize(new Dimension(200, 38));
        this.sensorRangeLabel4.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 0;
        this.SensorTreePanel.add(this.sensorRangeLabel4, localGridBagConstraints);
        this.xpLabel29.setFont(new Font("Moire", 0, 10));
        this.xpLabel29.setText("7500");
        this.xpLabel29.setAlignmentY(0.0F);
        this.xpLabel29.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel29.setMaximumSize(new Dimension(50, 38));
        this.xpLabel29.setMinimumSize(new Dimension(50, 38));
        this.xpLabel29.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 0;
        this.SensorTreePanel.add(this.xpLabel29, localGridBagConstraints);
        this.PilotTreeTabbedPane.addTab("Sensor", this.SensorTreePanel);
        this.SupportTreePanel.setMaximumSize(new Dimension(132, 300));
        this.SupportTreePanel.setMinimumSize(new Dimension(132, 300));
        this.SupportTreePanel.setPreferredSize(new Dimension(132, 300));
        this.SupportTreePanel.setLayout(new GridBagLayout());
        this.xpLabel11.setFont(new Font("Moire", 0, 10));
        this.xpLabel11.setText("15000");
        this.xpLabel11.setAlignmentY(0.0F);
        this.xpLabel11.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel11.setMaximumSize(new Dimension(50, 38));
        this.xpLabel11.setMinimumSize(new Dimension(50, 38));
        this.xpLabel11.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        this.SupportTreePanel.add(this.xpLabel11, localGridBagConstraints);
        this.infoGatherLabel1.setFont(new Font("Moire", 0, 10));
        this.infoGatherLabel1.setText("Capture Rate increased 15%");
        this.infoGatherLabel1.setAlignmentY(0.0F);
        this.infoGatherLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Capture Accelerator", 0, 0, new Font("Moire", 0, 11)));
        this.infoGatherLabel1.setMaximumSize(new Dimension(200, 38));
        this.infoGatherLabel1.setMinimumSize(new Dimension(200, 38));
        this.infoGatherLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        this.SupportTreePanel.add(this.infoGatherLabel1, localGridBagConstraints);
        this.xpLabel12.setFont(new Font("Moire", 0, 10));
        this.xpLabel12.setText("5000");
        this.xpLabel12.setAlignmentY(0.0F);
        this.xpLabel12.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel12.setEnabled(false);
        this.xpLabel12.setMaximumSize(new Dimension(50, 38));
        this.xpLabel12.setMinimumSize(new Dimension(50, 38));
        this.xpLabel12.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        this.SupportTreePanel.add(this.xpLabel12, localGridBagConstraints);
        this.hideDamageLabel1.setFont(new Font("Moire", 0, 10));
        this.hideDamageLabel1.setText("?");
        this.hideDamageLabel1.setAlignmentY(0.0F);
        this.hideDamageLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Friendly Defense", 0, 0, new Font("Moire", 0, 11)));
        this.hideDamageLabel1.setEnabled(false);
        this.hideDamageLabel1.setMaximumSize(new Dimension(200, 38));
        this.hideDamageLabel1.setMinimumSize(new Dimension(200, 38));
        this.hideDamageLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.SupportTreePanel.add(this.hideDamageLabel1, localGridBagConstraints);
        this.xpLabel13.setFont(new Font("Moire", 0, 10));
        this.xpLabel13.setText("5000");
        this.xpLabel13.setAlignmentY(0.0F);
        this.xpLabel13.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel13.setEnabled(false);
        this.xpLabel13.setMaximumSize(new Dimension(50, 38));
        this.xpLabel13.setMinimumSize(new Dimension(50, 38));
        this.xpLabel13.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 2;
        this.SupportTreePanel.add(this.xpLabel13, localGridBagConstraints);
        this.signalLossLabel1.setFont(new Font("Moire", 0, 10));
        this.signalLossLabel1.setText("?");
        this.signalLossLabel1.setAlignmentY(0.0F);
        this.signalLossLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Unit Vision Modes", 0, 0, new Font("Moire", 0, 11)));
        this.signalLossLabel1.setEnabled(false);
        this.signalLossLabel1.setMaximumSize(new Dimension(200, 38));
        this.signalLossLabel1.setMinimumSize(new Dimension(200, 38));
        this.signalLossLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        this.SupportTreePanel.add(this.signalLossLabel1, localGridBagConstraints);
        this.xpLabel14.setFont(new Font("Moire", 0, 10));
        this.xpLabel14.setText("5000");
        this.xpLabel14.setAlignmentY(0.0F);
        this.xpLabel14.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel14.setEnabled(false);
        this.xpLabel14.setMaximumSize(new Dimension(50, 38));
        this.xpLabel14.setMinimumSize(new Dimension(50, 38));
        this.xpLabel14.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 3;
        this.SupportTreePanel.add(this.xpLabel14, localGridBagConstraints);
        this.sensorRangeLabel1.setFont(new Font("Moire", 0, 10));
        this.sensorRangeLabel1.setText("?");
        this.sensorRangeLabel1.setAlignmentY(0.0F);
        this.sensorRangeLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Artillery Accuracy", 0, 0, new Font("Moire", 0, 11)));
        this.sensorRangeLabel1.setEnabled(false);
        this.sensorRangeLabel1.setMaximumSize(new Dimension(200, 38));
        this.sensorRangeLabel1.setMinimumSize(new Dimension(200, 38));
        this.sensorRangeLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 4;
        this.SupportTreePanel.add(this.sensorRangeLabel1, localGridBagConstraints);
        this.xpLabel15.setFont(new Font("Moire", 0, 10));
        this.xpLabel15.setText("5000");
        this.xpLabel15.setAlignmentY(0.0F);
        this.xpLabel15.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel15.setEnabled(false);
        this.xpLabel15.setMaximumSize(new Dimension(50, 38));
        this.xpLabel15.setMinimumSize(new Dimension(50, 38));
        this.xpLabel15.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 4;
        this.SupportTreePanel.add(this.xpLabel15, localGridBagConstraints);
        this.seismicLabel1.setFont(new Font("Moire", 0, 10));
        this.seismicLabel1.setText("?");
        this.seismicLabel1.setAlignmentY(0.0F);
        this.seismicLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Control Link", 0, 0, new Font("Moire", 0, 11)));
        this.seismicLabel1.setEnabled(false);
        this.seismicLabel1.setMaximumSize(new Dimension(200, 38));
        this.seismicLabel1.setMinimumSize(new Dimension(200, 38));
        this.seismicLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 5;
        this.SupportTreePanel.add(this.seismicLabel1, localGridBagConstraints);
        this.xpLabel16.setFont(new Font("Moire", 0, 10));
        this.xpLabel16.setText("5000");
        this.xpLabel16.setAlignmentY(0.0F);
        this.xpLabel16.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel16.setEnabled(false);
        this.xpLabel16.setMaximumSize(new Dimension(50, 38));
        this.xpLabel16.setMinimumSize(new Dimension(50, 38));
        this.xpLabel16.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 5;
        this.SupportTreePanel.add(this.xpLabel16, localGridBagConstraints);
        this.orbitalScanLabel1.setFont(new Font("Moire", 0, 10));
        this.orbitalScanLabel1.setText("?");
        this.orbitalScanLabel1.setAlignmentY(0.0F);
        this.orbitalScanLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Airstrike Accuracy", 0, 0, new Font("Moire", 0, 11)));
        this.orbitalScanLabel1.setEnabled(false);
        this.orbitalScanLabel1.setMaximumSize(new Dimension(200, 38));
        this.orbitalScanLabel1.setMinimumSize(new Dimension(200, 38));
        this.orbitalScanLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 3;
        this.SupportTreePanel.add(this.orbitalScanLabel1, localGridBagConstraints);
        this.xpLabel17.setFont(new Font("Moire", 0, 10));
        this.xpLabel17.setText("5000");
        this.xpLabel17.setAlignmentY(0.0F);
        this.xpLabel17.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel17.setEnabled(false);
        this.xpLabel17.setMaximumSize(new Dimension(50, 38));
        this.xpLabel17.setMinimumSize(new Dimension(50, 38));
        this.xpLabel17.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 6;
        this.SupportTreePanel.add(this.xpLabel17, localGridBagConstraints);
        this.magnetometerLabel1.setFont(new Font("Moire", 0, 10));
        this.magnetometerLabel1.setText("?");
        this.magnetometerLabel1.setAlignmentY(0.0F);
        this.magnetometerLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Drone", 0, 0, new Font("Moire", 0, 11)));
        this.magnetometerLabel1.setEnabled(false);
        this.magnetometerLabel1.setMaximumSize(new Dimension(200, 38));
        this.magnetometerLabel1.setMinimumSize(new Dimension(200, 38));
        this.magnetometerLabel1.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 6;
        this.SupportTreePanel.add(this.magnetometerLabel1, localGridBagConstraints);
        this.magnetometerLabel3.setFont(new Font("Moire", 0, 10));
        this.magnetometerLabel3.setText("?");
        this.magnetometerLabel3.setAlignmentY(0.0F);
        this.magnetometerLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Drone", 0, 0, new Font("Moire", 0, 11)));
        this.magnetometerLabel3.setEnabled(false);
        this.magnetometerLabel3.setMaximumSize(new Dimension(200, 38));
        this.magnetometerLabel3.setMinimumSize(new Dimension(200, 38));
        this.magnetometerLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 6;
        this.SupportTreePanel.add(this.magnetometerLabel3, localGridBagConstraints);
        this.xpLabel27.setFont(new Font("Moire", 0, 10));
        this.xpLabel27.setText("7500");
        this.xpLabel27.setAlignmentY(0.0F);
        this.xpLabel27.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel27.setEnabled(false);
        this.xpLabel27.setMaximumSize(new Dimension(50, 38));
        this.xpLabel27.setMinimumSize(new Dimension(50, 38));
        this.xpLabel27.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 6;
        this.SupportTreePanel.add(this.xpLabel27, localGridBagConstraints);
        this.PilotTreeTabbedPane.addTab("Support", this.SupportTreePanel);
        this.TargetingTreePanel.setMaximumSize(new Dimension(132, 300));
        this.TargetingTreePanel.setMinimumSize(new Dimension(132, 300));
        this.TargetingTreePanel.setPreferredSize(new Dimension(132, 300));
        this.TargetingTreePanel.setLayout(new GridBagLayout());
        this.xpLabel18.setFont(new Font("Moire", 0, 10));
        this.xpLabel18.setText("5000");
        this.xpLabel18.setAlignmentY(0.0F);
        this.xpLabel18.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel18.setEnabled(false);
        this.xpLabel18.setMaximumSize(new Dimension(50, 38));
        this.xpLabel18.setMinimumSize(new Dimension(50, 38));
        this.xpLabel18.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 5;
        this.TargetingTreePanel.add(this.xpLabel18, localGridBagConstraints);
        this.infoGatherLabel2.setFont(new Font("Moire", 0, 10));
        this.infoGatherLabel2.setText("?");
        this.infoGatherLabel2.setAlignmentY(0.0F);
        this.infoGatherLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Multi Target", 0, 0, new Font("Moire", 0, 11)));
        this.infoGatherLabel2.setEnabled(false);
        this.infoGatherLabel2.setMaximumSize(new Dimension(200, 38));
        this.infoGatherLabel2.setMinimumSize(new Dimension(200, 38));
        this.infoGatherLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 5;
        this.TargetingTreePanel.add(this.infoGatherLabel2, localGridBagConstraints);
        this.xpLabel19.setFont(new Font("Moire", 0, 10));
        this.xpLabel19.setText("5000");
        this.xpLabel19.setAlignmentY(0.0F);
        this.xpLabel19.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel19.setEnabled(false);
        this.xpLabel19.setMaximumSize(new Dimension(50, 38));
        this.xpLabel19.setMinimumSize(new Dimension(50, 38));
        this.xpLabel19.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        this.TargetingTreePanel.add(this.xpLabel19, localGridBagConstraints);
        this.hideDamageLabel2.setFont(new Font("Moire", 0, 10));
        this.hideDamageLabel2.setText("?");
        this.hideDamageLabel2.setAlignmentY(0.0F);
        this.hideDamageLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Targeting Delay", 0, 0, new Font("Moire", 0, 11)));
        this.hideDamageLabel2.setEnabled(false);
        this.hideDamageLabel2.setMaximumSize(new Dimension(200, 38));
        this.hideDamageLabel2.setMinimumSize(new Dimension(200, 38));
        this.hideDamageLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.TargetingTreePanel.add(this.hideDamageLabel2, localGridBagConstraints);
        this.xpLabel20.setFont(new Font("Moire", 0, 10));
        this.xpLabel20.setText("5000");
        this.xpLabel20.setAlignmentY(0.0F);
        this.xpLabel20.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel20.setEnabled(false);
        this.xpLabel20.setMaximumSize(new Dimension(50, 38));
        this.xpLabel20.setMinimumSize(new Dimension(50, 38));
        this.xpLabel20.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 2;
        this.TargetingTreePanel.add(this.xpLabel20, localGridBagConstraints);
        this.signalLossLabel2.setFont(new Font("Moire", 0, 10));
        this.signalLossLabel2.setText("?");
        this.signalLossLabel2.setAlignmentY(0.0F);
        this.signalLossLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Disrupt HUD", 0, 0, new Font("Moire", 0, 11)));
        this.signalLossLabel2.setEnabled(false);
        this.signalLossLabel2.setMaximumSize(new Dimension(200, 38));
        this.signalLossLabel2.setMinimumSize(new Dimension(200, 38));
        this.signalLossLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        this.TargetingTreePanel.add(this.signalLossLabel2, localGridBagConstraints);
        this.xpLabel21.setFont(new Font("Moire", 0, 10));
        this.xpLabel21.setText("5000");
        this.xpLabel21.setAlignmentY(0.0F);
        this.xpLabel21.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel21.setEnabled(false);
        this.xpLabel21.setMaximumSize(new Dimension(50, 38));
        this.xpLabel21.setMinimumSize(new Dimension(50, 38));
        this.xpLabel21.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 3;
        this.TargetingTreePanel.add(this.xpLabel21, localGridBagConstraints);
        this.sensorRangeLabel2.setFont(new Font("Moire", 0, 10));
        this.sensorRangeLabel2.setText("Increases Decay Time to 2.75 sec");
        this.sensorRangeLabel2.setAlignmentY(0.0F);
        this.sensorRangeLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Target Decay", 0, 0, new Font("Moire", 0, 11)));
        this.sensorRangeLabel2.setMaximumSize(new Dimension(200, 38));
        this.sensorRangeLabel2.setMinimumSize(new Dimension(200, 38));
        this.sensorRangeLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 4;
        this.TargetingTreePanel.add(this.sensorRangeLabel2, localGridBagConstraints);
        this.xpLabel22.setFont(new Font("Moire", 0, 10));
        this.xpLabel22.setText("5000");
        this.xpLabel22.setAlignmentY(0.0F);
        this.xpLabel22.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel22.setMaximumSize(new Dimension(50, 38));
        this.xpLabel22.setMinimumSize(new Dimension(50, 38));
        this.xpLabel22.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 4;
        this.TargetingTreePanel.add(this.xpLabel22, localGridBagConstraints);
        this.seismicLabel2.setFont(new Font("Moire", 0, 10));
        this.seismicLabel2.setText("Target stays on radar within 200m");
        this.seismicLabel2.setAlignmentY(0.0F);
        this.seismicLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "360 Radar", 0, 0, new Font("Moire", 0, 11)));
        this.seismicLabel2.setMaximumSize(new Dimension(200, 38));
        this.seismicLabel2.setMinimumSize(new Dimension(200, 38));
        this.seismicLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        this.TargetingTreePanel.add(this.seismicLabel2, localGridBagConstraints);
        this.xpLabel23.setFont(new Font("Moire", 0, 10));
        this.xpLabel23.setText("15000");
        this.xpLabel23.setAlignmentY(0.0F);
        this.xpLabel23.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel23.setMaximumSize(new Dimension(50, 38));
        this.xpLabel23.setMinimumSize(new Dimension(50, 38));
        this.xpLabel23.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        this.TargetingTreePanel.add(this.xpLabel23, localGridBagConstraints);
        this.orbitalScanLabel2.setFont(new Font("Moire", 0, 10));
        this.orbitalScanLabel2.setText("?");
        this.orbitalScanLabel2.setAlignmentY(0.0F);
        this.orbitalScanLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Disable Comms", 0, 0, new Font("Moire", 0, 11)));
        this.orbitalScanLabel2.setEnabled(false);
        this.orbitalScanLabel2.setMaximumSize(new Dimension(200, 38));
        this.orbitalScanLabel2.setMinimumSize(new Dimension(200, 38));
        this.orbitalScanLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 3;
        this.TargetingTreePanel.add(this.orbitalScanLabel2, localGridBagConstraints);
        this.xpLabel24.setFont(new Font("Moire", 0, 10));
        this.xpLabel24.setText("5000");
        this.xpLabel24.setAlignmentY(0.0F);
        this.xpLabel24.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel24.setEnabled(false);
        this.xpLabel24.setMaximumSize(new Dimension(50, 38));
        this.xpLabel24.setMinimumSize(new Dimension(50, 38));
        this.xpLabel24.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 6;
        this.TargetingTreePanel.add(this.xpLabel24, localGridBagConstraints);
        this.magnetometerLabel2.setFont(new Font("Moire", 0, 10));
        this.magnetometerLabel2.setText("?");
        this.magnetometerLabel2.setAlignmentY(0.0F);
        this.magnetometerLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Control Link", 0, 0, new Font("Moire", 0, 11)));
        this.magnetometerLabel2.setEnabled(false);
        this.magnetometerLabel2.setMaximumSize(new Dimension(200, 38));
        this.magnetometerLabel2.setMinimumSize(new Dimension(200, 38));
        this.magnetometerLabel2.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 6;
        this.TargetingTreePanel.add(this.magnetometerLabel2, localGridBagConstraints);
        this.xpLabel25.setFont(new Font("Moire", 0, 10));
        this.xpLabel25.setText("7500");
        this.xpLabel25.setAlignmentY(0.0F);
        this.xpLabel25.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel25.setEnabled(false);
        this.xpLabel25.setMaximumSize(new Dimension(50, 38));
        this.xpLabel25.setMinimumSize(new Dimension(50, 38));
        this.xpLabel25.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 5;
        this.TargetingTreePanel.add(this.xpLabel25, localGridBagConstraints);
        this.infoGatherLabel3.setFont(new Font("Moire", 0, 10));
        this.infoGatherLabel3.setText("?");
        this.infoGatherLabel3.setAlignmentY(0.0F);
        this.infoGatherLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Multi Target", 0, 0, new Font("Moire", 0, 11)));
        this.infoGatherLabel3.setEnabled(false);
        this.infoGatherLabel3.setMaximumSize(new Dimension(200, 38));
        this.infoGatherLabel3.setMinimumSize(new Dimension(200, 38));
        this.infoGatherLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 5;
        this.TargetingTreePanel.add(this.infoGatherLabel3, localGridBagConstraints);
        this.sensorRangeLabel3.setFont(new Font("Moire", 0, 10));
        this.sensorRangeLabel3.setText("Increases Decay Time to 3.5 sec");
        this.sensorRangeLabel3.setAlignmentY(0.0F);
        this.sensorRangeLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Target Decay", 0, 0, new Font("Moire", 0, 11)));
        this.sensorRangeLabel3.setMaximumSize(new Dimension(200, 38));
        this.sensorRangeLabel3.setMinimumSize(new Dimension(200, 38));
        this.sensorRangeLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 3;
        localGridBagConstraints.gridy = 4;
        this.TargetingTreePanel.add(this.sensorRangeLabel3, localGridBagConstraints);
        this.xpLabel26.setFont(new Font("Moire", 0, 10));
        this.xpLabel26.setText("7500");
        this.xpLabel26.setAlignmentY(0.0F);
        this.xpLabel26.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel26.setMaximumSize(new Dimension(50, 38));
        this.xpLabel26.setMinimumSize(new Dimension(50, 38));
        this.xpLabel26.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 2;
        localGridBagConstraints.gridy = 4;
        this.TargetingTreePanel.add(this.xpLabel26, localGridBagConstraints);
        this.PilotTreeTabbedPane.addTab("Targeting", this.TargetingTreePanel);
        this.TargetingTreePanel1.setMaximumSize(new Dimension(132, 300));
        this.TargetingTreePanel1.setMinimumSize(new Dimension(132, 300));
        this.TargetingTreePanel1.setPreferredSize(new Dimension(132, 300));
        this.TargetingTreePanel1.setLayout(new GridBagLayout());
        this.xpLabel31.setFont(new Font("Moire", 0, 10));
        this.xpLabel31.setText("15000");
        this.xpLabel31.setAlignmentY(0.0F);
        this.xpLabel31.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel31.setMaximumSize(new Dimension(50, 38));
        this.xpLabel31.setMinimumSize(new Dimension(50, 38));
        this.xpLabel31.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 1;
        this.TargetingTreePanel1.add(this.xpLabel31, localGridBagConstraints);
        this.hideDamageLabel3.setFont(new Font("Moire", 0, 10));
        this.hideDamageLabel3.setText("Cool Shot 9 By 9 effect doubled");
        this.hideDamageLabel3.setAlignmentY(0.0F);
        this.hideDamageLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cool Shot 9 By 9", 0, 0, new Font("Moire", 0, 11), new Color(0, 0, 0)));
        this.hideDamageLabel3.setMaximumSize(new Dimension(200, 38));
        this.hideDamageLabel3.setMinimumSize(new Dimension(200, 38));
        this.hideDamageLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 1;
        this.TargetingTreePanel1.add(this.hideDamageLabel3, localGridBagConstraints);
        this.xpLabel32.setFont(new Font("Moire", 0, 10));
        this.xpLabel32.setText("15000");
        this.xpLabel32.setAlignmentY(0.0F);
        this.xpLabel32.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel32.setMaximumSize(new Dimension(50, 38));
        this.xpLabel32.setMinimumSize(new Dimension(50, 38));
        this.xpLabel32.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 2;
        this.TargetingTreePanel1.add(this.xpLabel32, localGridBagConstraints);
        this.signalLossLabel3.setFont(new Font("Moire", 0, 10));
        this.signalLossLabel3.setText("Adds 4 shells and reduces delay");
        this.signalLossLabel3.setAlignmentY(0.0F);
        this.signalLossLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Improved Artillery Strike", 0, 0, new Font("Moire", 0, 11)));
        this.signalLossLabel3.setMaximumSize(new Dimension(200, 38));
        this.signalLossLabel3.setMinimumSize(new Dimension(200, 38));
        this.signalLossLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 2;
        this.TargetingTreePanel1.add(this.signalLossLabel3, localGridBagConstraints);
        this.xpLabel33.setFont(new Font("Moire", 0, 10));
        this.xpLabel33.setText("15000");
        this.xpLabel33.setAlignmentY(0.0F);
        this.xpLabel33.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel33.setMaximumSize(new Dimension(50, 38));
        this.xpLabel33.setMinimumSize(new Dimension(50, 38));
        this.xpLabel33.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 3;
        this.TargetingTreePanel1.add(this.xpLabel33, localGridBagConstraints);
        this.seismicLabel4.setFont(new Font("Moire", 0, 10));
        this.seismicLabel4.setText("Cool Shots effect improved by 20%");
        this.seismicLabel4.setAlignmentY(0.0F);
        this.seismicLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cool Boost", 0, 0, new Font("Moire", 0, 11)));
        this.seismicLabel4.setMaximumSize(new Dimension(200, 38));
        this.seismicLabel4.setMinimumSize(new Dimension(200, 38));
        this.seismicLabel4.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        this.TargetingTreePanel1.add(this.seismicLabel4, localGridBagConstraints);
        this.xpLabel35.setFont(new Font("Moire", 0, 10));
        this.xpLabel35.setText("15000");
        this.xpLabel35.setAlignmentY(0.0F);
        this.xpLabel35.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", 0, 0, new Font("Moire", 0, 11)));
        this.xpLabel35.setMaximumSize(new Dimension(50, 38));
        this.xpLabel35.setMinimumSize(new Dimension(50, 38));
        this.xpLabel35.setPreferredSize(new Dimension(50, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        this.TargetingTreePanel1.add(this.xpLabel35, localGridBagConstraints);
        this.orbitalScanLabel3.setFont(new Font("Moire", 0, 10));
        this.orbitalScanLabel3.setText("Adds 4 shells and reduces delay");
        this.orbitalScanLabel3.setAlignmentY(0.0F);
        this.orbitalScanLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Improved Air Strike", 0, 0, new Font("Moire", 0, 11)));
        this.orbitalScanLabel3.setMaximumSize(new Dimension(200, 38));
        this.orbitalScanLabel3.setMinimumSize(new Dimension(200, 38));
        this.orbitalScanLabel3.setPreferredSize(new Dimension(200, 38));
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 3;
        this.TargetingTreePanel1.add(this.orbitalScanLabel3, localGridBagConstraints);
        this.PilotTreeTabbedPane.addTab("Consumables", this.TargetingTreePanel1);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.PilotTreeTabbedPane, localGridBagConstraints);
        this.ButtonPanel.setMaximumSize(new Dimension(132, 300));
        this.ButtonPanel.setMinimumSize(new Dimension(132, 300));
        this.ButtonPanel.setPreferredSize(new Dimension(132, 300));
        this.ButtonPanel.setLayout(new GridBagLayout());
        this.closeButton.setFont(new Font("Moire", 0, 12));
        this.closeButton.setText("Close");
        this.closeButton.setMaximumSize(new Dimension(120, 30));
        this.closeButton.setMinimumSize(new Dimension(120, 30));
        this.closeButton.setPreferredSize(new Dimension(120, 30));
        this.closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent paramAnonymousActionEvent) {
                PilotTreeDialogBox.this.closeButtonActionPerformed(paramAnonymousActionEvent);
            }
        });
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 0;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        this.ButtonPanel.add(this.closeButton, localGridBagConstraints);
        localGridBagConstraints = new GridBagConstraints();
        localGridBagConstraints.gridx = 1;
        localGridBagConstraints.gridy = 0;
        localGridBagConstraints.weightx = 1.0D;
        localGridBagConstraints.weighty = 1.0D;
        getContentPane().add(this.ButtonPanel, localGridBagConstraints);
        pack();
    }

    private void closeButtonActionPerformed(ActionEvent paramActionEvent) {
        dispose();
    }
}
