/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MWOMechbay.GUI;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.*;

/**
 *
 * @author Nemesis
 */
public class AboutDialogBox extends javax.swing.JDialog
{
    
    public AboutDialogBox(java.awt.Frame parent, boolean modal, String programVersion, String MWOstage)
    {
        super(parent, modal);
        initComponents();
        this.setTitle("About " + parent.getTitle());
        titleLabel.setText(parent.getTitle());
        versionLabel.setText(programVersion);
        MWOLabel.setText(MWOstage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        closeButton = new JButton();
        insigniaLabel = new JLabel();
        titleLabel = new JLabel();
        versionTitle = new JLabel();
        versionLabel = new JLabel();
        authorTitle = new JLabel();
        authorLabel = new JLabel();
        emailLabel = new JLabel();
        emailTitle = new JLabel();
        disclaimerLabel = new JLabel();
        MWOLabel = new JLabel();
        MWOTitle = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About MWO Mechbay");
        setAlwaysOnTop(true);
        setMinimumSize(new Dimension(432, 144));
        setName("About"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new GridBagLayout());

        closeButton.setFont(new Font("Moire", 0, 11)); // NOI18N
        closeButton.setText("Close");
        closeButton.setMaximumSize(new Dimension(96, 24));
        closeButton.setMinimumSize(new Dimension(96, 24));
        closeButton.setPreferredSize(new Dimension(96, 24));
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(closeButton, gridBagConstraints);
        getRootPane().setDefaultButton(closeButton);

        insigniaLabel.setHorizontalAlignment(SwingConstants.CENTER);
        insigniaLabel.setIcon(new ImageIcon(getClass().getResource("/MWOMechbay/Resources/Widowmaker Insignia.gif"))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        getContentPane().add(insigniaLabel, gridBagConstraints);

        titleLabel.setFont(new Font("Moire", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setText("MWO Mechbay");
        titleLabel.setMaximumSize(new Dimension(288, 36));
        titleLabel.setMinimumSize(new Dimension(288, 36));
        titleLabel.setPreferredSize(new Dimension(288, 36));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(titleLabel, gridBagConstraints);

        versionTitle.setFont(new Font("Moire", 0, 11)); // NOI18N
        versionTitle.setHorizontalAlignment(SwingConstants.CENTER);
        versionTitle.setText("Version:");
        versionTitle.setMaximumSize(new Dimension(96, 18));
        versionTitle.setMinimumSize(new Dimension(96, 18));
        versionTitle.setPreferredSize(new Dimension(96, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(versionTitle, gridBagConstraints);

        versionLabel.setFont(new Font("Moire", 0, 11)); // NOI18N
        versionLabel.setText("0.0.0");
        versionLabel.setMaximumSize(new Dimension(192, 18));
        versionLabel.setMinimumSize(new Dimension(192, 18));
        versionLabel.setPreferredSize(new Dimension(192, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(versionLabel, gridBagConstraints);

        authorTitle.setFont(new Font("Moire", 0, 11)); // NOI18N
        authorTitle.setHorizontalAlignment(SwingConstants.CENTER);
        authorTitle.setText("Author:");
        authorTitle.setMaximumSize(new Dimension(96, 18));
        authorTitle.setMinimumSize(new Dimension(96, 18));
        authorTitle.setPreferredSize(new Dimension(96, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(authorTitle, gridBagConstraints);

        authorLabel.setFont(new Font("Moire", 0, 11)); // NOI18N
        authorLabel.setText("=WM=Quicksilver");
        authorLabel.setMaximumSize(new Dimension(192, 18));
        authorLabel.setMinimumSize(new Dimension(192, 18));
        authorLabel.setPreferredSize(new Dimension(192, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(authorLabel, gridBagConstraints);

        emailLabel.setFont(new Font("Moire", 0, 11)); // NOI18N
        emailLabel.setText("cjf-qssb@hotmail.com");
        emailLabel.setMaximumSize(new Dimension(192, 18));
        emailLabel.setMinimumSize(new Dimension(192, 18));
        emailLabel.setPreferredSize(new Dimension(192, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(emailLabel, gridBagConstraints);

        emailTitle.setFont(new Font("Moire", 0, 11)); // NOI18N
        emailTitle.setHorizontalAlignment(SwingConstants.CENTER);
        emailTitle.setText("E-Mail:");
        emailTitle.setMaximumSize(new Dimension(96, 18));
        emailTitle.setMinimumSize(new Dimension(96, 18));
        emailTitle.setPreferredSize(new Dimension(96, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(emailTitle, gridBagConstraints);

        disclaimerLabel.setFont(new Font("Moire", 0, 13)); // NOI18N
        disclaimerLabel.setHorizontalAlignment(SwingConstants.CENTER);
        disclaimerLabel.setText("Unofficial Program for MWO");
        disclaimerLabel.setMaximumSize(new Dimension(192, 36));
        disclaimerLabel.setMinimumSize(new Dimension(192, 36));
        disclaimerLabel.setPreferredSize(new Dimension(192, 36));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(disclaimerLabel, gridBagConstraints);

        MWOLabel.setFont(new Font("Moire", 0, 11)); // NOI18N
        MWOLabel.setText("0.0.0");
        MWOLabel.setMaximumSize(new Dimension(192, 18));
        MWOLabel.setMinimumSize(new Dimension(192, 18));
        MWOLabel.setPreferredSize(new Dimension(192, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(MWOLabel, gridBagConstraints);

        MWOTitle.setFont(new Font("Moire", 0, 11)); // NOI18N
        MWOTitle.setHorizontalAlignment(SwingConstants.CENTER);
        MWOTitle.setText("MWO Stage:");
        MWOTitle.setMaximumSize(new Dimension(96, 18));
        MWOTitle.setMinimumSize(new Dimension(96, 18));
        MWOTitle.setPreferredSize(new Dimension(96, 18));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(MWOTitle, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel MWOLabel;
    private JLabel MWOTitle;
    private JLabel authorLabel;
    private JLabel authorTitle;
    private JButton closeButton;
    private JLabel disclaimerLabel;
    private JLabel emailLabel;
    private JLabel emailTitle;
    private JLabel insigniaLabel;
    private JLabel titleLabel;
    private JLabel versionLabel;
    private JLabel versionTitle;
    // End of variables declaration//GEN-END:variables
}
