/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MWOMechbay.GUI;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.*;


/**
 *
 * @author Quicksilver
 */
public class EditDialogBox extends javax.swing.JDialog {

    Vector<String> groupTemp;
    DefaultListModel groupListModel = new DefaultListModel();
    
    public EditDialogBox(java.awt.Frame parent, boolean modal, Vector<String> groups) {
        super(parent, modal);
        groupTemp = groups;
        for (int i = 0; i < groupTemp.size(); i++)
            groupListModel.addElement(groupTemp.elementAt(i));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        doneButton = new JButton();
        newGroupName = new JTextField();
        addButton = new JButton();
        removeButton = new JButton();
        groupScrollPane = new JScrollPane();
        groupList = new JList(groupTemp);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);
        setMaximumSize(new Dimension(200, 300));
        setMinimumSize(new Dimension(200, 300));
        setName("createGroupDialogBox");
        setPreferredSize(new Dimension(200, 300));
        setResizable(false);
        getContentPane().setLayout(new GridBagLayout());

        doneButton.setFont(doneButton.getFont().deriveFont((float)10));
        doneButton.setText("Done");
        doneButton.setMaximumSize(new Dimension(90, 25));
        doneButton.setMinimumSize(new Dimension(90, 25));
        doneButton.setPreferredSize(new Dimension(90, 25));
        doneButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(doneButton, gridBagConstraints);

        newGroupName.setFont(newGroupName.getFont().deriveFont((float)10));
        newGroupName.setMaximumSize(new Dimension(200, 30));
        newGroupName.setMinimumSize(new Dimension(200, 30));
        newGroupName.setPreferredSize(new Dimension(200, 30));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(newGroupName, gridBagConstraints);

        addButton.setFont(addButton.getFont().deriveFont((float)10));
        addButton.setText("Add");
        addButton.setMaximumSize(new Dimension(90, 25));
        addButton.setMinimumSize(new Dimension(90, 25));
        addButton.setPreferredSize(new Dimension(90, 25));
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(addButton, gridBagConstraints);

        removeButton.setFont(removeButton.getFont().deriveFont((float)10));
        removeButton.setText("Remove");
        removeButton.setMaximumSize(new Dimension(90, 25));
        removeButton.setMinimumSize(new Dimension(90, 25));
        removeButton.setPreferredSize(new Dimension(90, 25));
        removeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(removeButton, gridBagConstraints);

        groupScrollPane.setMaximumSize(new Dimension(200, 210));
        groupScrollPane.setMinimumSize(new Dimension(200, 210));
        groupScrollPane.setPreferredSize(new Dimension(200, 210));

        groupList.setFont(groupList.getFont().deriveFont((float)10));
        groupList.setModel(groupListModel);
        groupList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        groupScrollPane.setViewportView(groupList);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(groupScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void doneButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void addButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        groupTemp.addElement(newGroupName.getText());
        newGroupName.setText("");
        groupListModel.removeAllElements();
        for (int i = 0; i < groupTemp.size(); i++)
            groupListModel.addElement(groupTemp.elementAt(i));
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int tempIndex = groupList.getSelectedIndex();
        groupTemp.removeElementAt(tempIndex);
        groupListModel.removeElementAt(tempIndex);
    }//GEN-LAST:event_removeButtonActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addButton;
    private JButton doneButton;
    private JList groupList;
    private JScrollPane groupScrollPane;
    private JTextField newGroupName;
    private JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
