/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MWOMechbay.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Nemesis
 */
public class MechTreeDialogBox extends javax.swing.JDialog
{   
    public MechTreeDialogBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable( false );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        BasicPanel = new JPanel();
        xpLabel1 = new JLabel();
        twistXLabel = new JLabel();
        xpLabel2 = new JLabel();
        anchorTurnLabel = new JLabel();
        xpLabel3 = new JLabel();
        hardBrakeLabel = new JLabel();
        xpLabel4 = new JLabel();
        kineticBurstLabel = new JLabel();
        xpLabel5 = new JLabel();
        twistSpeedLabel = new JLabel();
        xpLabel6 = new JLabel();
        armReflexLabel = new JLabel();
        xpLabel7 = new JLabel();
        coolrunLabel = new JLabel();
        xpLabel8 = new JLabel();
        heatContainmentLabel = new JLabel();
        ElitePanel = new JPanel();
        xpLabel9 = new JLabel();
        pinpointLabel = new JLabel();
        xpLabel10 = new JLabel();
        speedTweakLabel = new JLabel();
        xpLabel11 = new JLabel();
        fastFireLabel = new JLabel();
        xpLabel12 = new JLabel();
        quickIgnitionLabel = new JLabel();
        MasterPanel = new JPanel();
        xpLabel13 = new JLabel();
        pinpointLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        ButtonPanel = new JPanel();
        closeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mech Trees");
        setMinimumSize(new Dimension(700, 300));
        setName("MechTreeDialog"); // NOI18N
        getContentPane().setLayout(new GridBagLayout());

        BasicPanel.setBackground(new Color(64, 128, 255));
        BasicPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Basic", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        BasicPanel.setOpaque(false);
        BasicPanel.setLayout(new GridBagLayout());

        xpLabel1.setBackground(new Color(64, 128, 255));
        xpLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel1.setText("2500");
        xpLabel1.setAlignmentY(0.0F);
        xpLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel1, gridBagConstraints);

        twistXLabel.setBackground(new Color(64, 128, 255));
        twistXLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        twistXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        twistXLabel.setText("Torso Twist Range +10.0%");
        twistXLabel.setAlignmentY(0.0F);
        twistXLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Twist X", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(twistXLabel, gridBagConstraints);

        xpLabel2.setBackground(new Color(64, 128, 255));
        xpLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel2.setText("3500");
        xpLabel2.setAlignmentY(0.0F);
        xpLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel2, gridBagConstraints);

        anchorTurnLabel.setBackground(new Color(64, 128, 255));
        anchorTurnLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        anchorTurnLabel.setHorizontalAlignment(SwingConstants.CENTER);
        anchorTurnLabel.setText("Turning Speed +10.0%");
        anchorTurnLabel.setAlignmentY(0.0F);
        anchorTurnLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Anchor Turn", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(anchorTurnLabel, gridBagConstraints);

        xpLabel3.setBackground(new Color(64, 128, 255));
        xpLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel3.setText("1500");
        xpLabel3.setAlignmentY(0.0F);
        xpLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel3, gridBagConstraints);

        hardBrakeLabel.setBackground(new Color(64, 128, 255));
        hardBrakeLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        hardBrakeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        hardBrakeLabel.setText("Decceleration +25%");
        hardBrakeLabel.setAlignmentY(0.0F);
        hardBrakeLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Hard Brake", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(hardBrakeLabel, gridBagConstraints);

        xpLabel4.setBackground(new Color(64, 128, 255));
        xpLabel4.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel4.setText("1000");
        xpLabel4.setAlignmentY(0.0F);
        xpLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel4, gridBagConstraints);

        kineticBurstLabel.setBackground(new Color(64, 128, 255));
        kineticBurstLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        kineticBurstLabel.setHorizontalAlignment(SwingConstants.CENTER);
        kineticBurstLabel.setText("Acceleration +22.5%");
        kineticBurstLabel.setAlignmentY(0.0F);
        kineticBurstLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Kinetic Burst", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(kineticBurstLabel, gridBagConstraints);

        xpLabel5.setBackground(new Color(64, 128, 255));
        xpLabel5.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel5.setText("1500");
        xpLabel5.setAlignmentY(0.0F);
        xpLabel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel5, gridBagConstraints);

        twistSpeedLabel.setBackground(new Color(64, 128, 255));
        twistSpeedLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        twistSpeedLabel.setHorizontalAlignment(SwingConstants.CENTER);
        twistSpeedLabel.setText("Twist Speed +15.0%");
        twistSpeedLabel.setAlignmentY(0.0F);
        twistSpeedLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Twist Speed", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(twistSpeedLabel, gridBagConstraints);

        xpLabel6.setBackground(new Color(64, 128, 255));
        xpLabel6.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel6.setText("2500");
        xpLabel6.setAlignmentY(0.0F);
        xpLabel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel6, gridBagConstraints);

        armReflexLabel.setBackground(new Color(64, 128, 255));
        armReflexLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        armReflexLabel.setHorizontalAlignment(SwingConstants.CENTER);
        armReflexLabel.setText("Arm Speed +20.0%");
        armReflexLabel.setAlignmentY(0.0F);
        armReflexLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Arm Reflex", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(armReflexLabel, gridBagConstraints);

        xpLabel7.setBackground(new Color(64, 128, 255));
        xpLabel7.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel7.setText("750");
        xpLabel7.setAlignmentY(0.0F);
        xpLabel7.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel7, gridBagConstraints);

        coolrunLabel.setBackground(new Color(64, 128, 255));
        coolrunLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        coolrunLabel.setHorizontalAlignment(SwingConstants.CENTER);
        coolrunLabel.setText("Heat Dissipation +7.5%");
        coolrunLabel.setAlignmentY(0.0F);
        coolrunLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cool Run", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(coolrunLabel, gridBagConstraints);

        xpLabel8.setBackground(new Color(64, 128, 255));
        xpLabel8.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel8.setText("1000");
        xpLabel8.setAlignmentY(0.0F);
        xpLabel8.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(xpLabel8, gridBagConstraints);

        heatContainmentLabel.setBackground(new Color(64, 128, 255));
        heatContainmentLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        heatContainmentLabel.setHorizontalAlignment(SwingConstants.CENTER);
        heatContainmentLabel.setText("Heat Threshold +10.0%");
        heatContainmentLabel.setAlignmentY(0.0F);
        heatContainmentLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Heat Containment", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        BasicPanel.add(heatContainmentLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(BasicPanel, gridBagConstraints);

        ElitePanel.setBackground(new Color(64, 255, 64));
        ElitePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Elite", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        ElitePanel.setOpaque(false);
        ElitePanel.setLayout(new GridBagLayout());

        xpLabel9.setBackground(new Color(64, 255, 64));
        xpLabel9.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel9.setText("3000");
        xpLabel9.setAlignmentY(0.0F);
        xpLabel9.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(xpLabel9, gridBagConstraints);

        pinpointLabel.setBackground(new Color(64, 255, 64));
        pinpointLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        pinpointLabel.setHorizontalAlignment(SwingConstants.CENTER);
        pinpointLabel.setText("Weapon Convergence +15.0%");
        pinpointLabel.setAlignmentY(0.0F);
        pinpointLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Pinpoint", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(pinpointLabel, gridBagConstraints);

        xpLabel10.setBackground(new Color(64, 255, 64));
        xpLabel10.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel10.setText("8500");
        xpLabel10.setAlignmentY(0.0F);
        xpLabel10.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(xpLabel10, gridBagConstraints);

        speedTweakLabel.setBackground(new Color(64, 255, 64));
        speedTweakLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        speedTweakLabel.setHorizontalAlignment(SwingConstants.CENTER);
        speedTweakLabel.setText("Top Speed +10%");
        speedTweakLabel.setAlignmentY(0.0F);
        speedTweakLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Speed Tweak", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(speedTweakLabel, gridBagConstraints);

        xpLabel11.setBackground(new Color(64, 255, 64));
        xpLabel11.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel11.setText("6000");
        xpLabel11.setAlignmentY(0.0F);
        xpLabel11.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(xpLabel11, gridBagConstraints);

        fastFireLabel.setBackground(new Color(64, 255, 64));
        fastFireLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        fastFireLabel.setHorizontalAlignment(SwingConstants.CENTER);
        fastFireLabel.setText("Weapon Cooldown -5.0%");
        fastFireLabel.setAlignmentY(0.0F);
        fastFireLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Fast Fire", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(fastFireLabel, gridBagConstraints);

        xpLabel12.setBackground(new Color(64, 255, 64));
        xpLabel12.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel12.setText("4000");
        xpLabel12.setAlignmentY(0.0F);
        xpLabel12.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(xpLabel12, gridBagConstraints);

        quickIgnitionLabel.setBackground(new Color(64, 255, 64));
        quickIgnitionLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        quickIgnitionLabel.setHorizontalAlignment(SwingConstants.CENTER);
        quickIgnitionLabel.setText("Start/Shutdown Speed +33%");
        quickIgnitionLabel.setAlignmentY(0.0F);
        quickIgnitionLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Quick Ignition", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ElitePanel.add(quickIgnitionLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(ElitePanel, gridBagConstraints);

        MasterPanel.setBackground(new Color(255, 255, 64));
        MasterPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Master", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        MasterPanel.setOpaque(false);
        MasterPanel.setLayout(new GridBagLayout());

        xpLabel13.setBackground(new Color(255, 255, 64));
        xpLabel13.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        xpLabel13.setText("21500");
        xpLabel13.setAlignmentY(0.0F);
        xpLabel13.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MasterPanel.add(xpLabel13, gridBagConstraints);

        pinpointLabel1.setBackground(new Color(255, 255, 64));
        pinpointLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        pinpointLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        pinpointLabel1.setText("1 Additional Module");
        pinpointLabel1.setAlignmentY(0.0F);
        pinpointLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Module Slot", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MasterPanel.add(pinpointLabel1, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(MasterPanel, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new Font("Moire", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("*Elite requires 3 variants to have all 8        Basic upgrades.\n\n*Master requires 3 variants in the same   weight class to have Elite status.\n\n*Elite status doubles all Basic upgrades.");
        jTextArea1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Notes", TitledBorder.CENTER, TitledBorder.TOP, new Font("Moire", 0, 11))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        ButtonPanel.setLayout(new GridBagLayout());

        closeButton.setFont(new Font("Moire", 0, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.setMaximumSize(new Dimension(120, 30));
        closeButton.setMinimumSize(new Dimension(120, 30));
        closeButton.setPreferredSize(new Dimension(110, 30));
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        ButtonPanel.add(closeButton, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(ButtonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel BasicPanel;
    private JPanel ButtonPanel;
    private JPanel ElitePanel;
    private JPanel MasterPanel;
    private JLabel anchorTurnLabel;
    private JLabel armReflexLabel;
    JButton closeButton;
    private JLabel coolrunLabel;
    private JLabel fastFireLabel;
    private JLabel hardBrakeLabel;
    private JLabel heatContainmentLabel;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private JLabel kineticBurstLabel;
    private JLabel pinpointLabel;
    private JLabel pinpointLabel1;
    private JLabel quickIgnitionLabel;
    private JLabel speedTweakLabel;
    private JLabel twistSpeedLabel;
    private JLabel twistXLabel;
    private JLabel xpLabel1;
    private JLabel xpLabel10;
    private JLabel xpLabel11;
    private JLabel xpLabel12;
    private JLabel xpLabel13;
    private JLabel xpLabel2;
    private JLabel xpLabel3;
    private JLabel xpLabel4;
    private JLabel xpLabel5;
    private JLabel xpLabel6;
    private JLabel xpLabel7;
    private JLabel xpLabel8;
    private JLabel xpLabel9;
    // End of variables declaration//GEN-END:variables
}
