/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MWOMechbay.GUI;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Nemesis
 */
public class PilotTreeDialogBox extends javax.swing.JDialog
{   
    public PilotTreeDialogBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable( false );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        PilotTreeTabbedPane = new JTabbedPane();
        VisionTreePanel = new JPanel();
        xpLabel1 = new JLabel();
        advZoomLabel = new JLabel();
        xpLabel2 = new JLabel();
        zoomDisruptorLabel = new JLabel();
        xpLabel3 = new JLabel();
        modeEnhanceLabel = new JLabel();
        SensorTreePanel = new JPanel();
        xpLabel4 = new JLabel();
        infoGatherLabel = new JLabel();
        xpLabel5 = new JLabel();
        hideDamageLabel = new JLabel();
        xpLabel6 = new JLabel();
        signalLossLabel = new JLabel();
        xpLabel7 = new JLabel();
        sensorRangeLabel = new JLabel();
        xpLabel8 = new JLabel();
        seismicLabel = new JLabel();
        xpLabel9 = new JLabel();
        orbitalScanLabel = new JLabel();
        xpLabel10 = new JLabel();
        magnetometerLabel = new JLabel();
        seismicLabel3 = new JLabel();
        xpLabel28 = new JLabel();
        sensorRangeLabel4 = new JLabel();
        xpLabel29 = new JLabel();
        SupportTreePanel = new JPanel();
        xpLabel11 = new JLabel();
        infoGatherLabel1 = new JLabel();
        xpLabel12 = new JLabel();
        hideDamageLabel1 = new JLabel();
        xpLabel13 = new JLabel();
        signalLossLabel1 = new JLabel();
        xpLabel14 = new JLabel();
        sensorRangeLabel1 = new JLabel();
        xpLabel15 = new JLabel();
        seismicLabel1 = new JLabel();
        xpLabel16 = new JLabel();
        orbitalScanLabel1 = new JLabel();
        xpLabel17 = new JLabel();
        magnetometerLabel1 = new JLabel();
        magnetometerLabel3 = new JLabel();
        xpLabel27 = new JLabel();
        TargetingTreePanel = new JPanel();
        xpLabel18 = new JLabel();
        infoGatherLabel2 = new JLabel();
        xpLabel19 = new JLabel();
        hideDamageLabel2 = new JLabel();
        xpLabel20 = new JLabel();
        signalLossLabel2 = new JLabel();
        xpLabel21 = new JLabel();
        sensorRangeLabel2 = new JLabel();
        xpLabel22 = new JLabel();
        seismicLabel2 = new JLabel();
        xpLabel23 = new JLabel();
        orbitalScanLabel2 = new JLabel();
        xpLabel24 = new JLabel();
        magnetometerLabel2 = new JLabel();
        xpLabel25 = new JLabel();
        infoGatherLabel3 = new JLabel();
        sensorRangeLabel3 = new JLabel();
        xpLabel26 = new JLabel();
        ButtonPanel = new JPanel();
        closeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pilot Trees");
        setMinimumSize(new Dimension(650, 350));
        setName("PilotTreeDialog"); // NOI18N
        getContentPane().setLayout(new GridBagLayout());

        PilotTreeTabbedPane.setAlignmentX(0.0F);
        PilotTreeTabbedPane.setAlignmentY(0.0F);
        PilotTreeTabbedPane.setFont(new Font("Moire", 0, 12)); // NOI18N
        PilotTreeTabbedPane.setMaximumSize(new Dimension(520, 300));
        PilotTreeTabbedPane.setMinimumSize(new Dimension(520, 300));
        PilotTreeTabbedPane.setPreferredSize(new Dimension(520, 300));

        VisionTreePanel.setMaximumSize(new Dimension(132, 300));
        VisionTreePanel.setMinimumSize(new Dimension(132, 300));
        VisionTreePanel.setPreferredSize(new Dimension(132, 300));
        VisionTreePanel.setLayout(new GridBagLayout());

        xpLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel1.setText("5000");
        xpLabel1.setAlignmentY(0.0F);
        xpLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel1.setMaximumSize(new Dimension(50, 38));
        xpLabel1.setMinimumSize(new Dimension(50, 38));
        xpLabel1.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        VisionTreePanel.add(xpLabel1, gridBagConstraints);

        advZoomLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        advZoomLabel.setText("PIP 4x Zoom");
        advZoomLabel.setAlignmentY(0.0F);
        advZoomLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Zoom", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        advZoomLabel.setMaximumSize(new Dimension(200, 38));
        advZoomLabel.setMinimumSize(new Dimension(200, 38));
        advZoomLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        VisionTreePanel.add(advZoomLabel, gridBagConstraints);

        xpLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel2.setText("5000");
        xpLabel2.setAlignmentY(0.0F);
        xpLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel2.setEnabled(false);
        xpLabel2.setMaximumSize(new Dimension(50, 38));
        xpLabel2.setMinimumSize(new Dimension(50, 38));
        xpLabel2.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        VisionTreePanel.add(xpLabel2, gridBagConstraints);

        zoomDisruptorLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        zoomDisruptorLabel.setText("?");
        zoomDisruptorLabel.setAlignmentY(0.0F);
        zoomDisruptorLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Vision Mode Disruptor", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        zoomDisruptorLabel.setEnabled(false);
        zoomDisruptorLabel.setMaximumSize(new Dimension(200, 38));
        zoomDisruptorLabel.setMinimumSize(new Dimension(200, 38));
        zoomDisruptorLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        VisionTreePanel.add(zoomDisruptorLabel, gridBagConstraints);

        xpLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel3.setText("5000");
        xpLabel3.setAlignmentY(0.0F);
        xpLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel3.setEnabled(false);
        xpLabel3.setMaximumSize(new Dimension(50, 38));
        xpLabel3.setMinimumSize(new Dimension(50, 38));
        xpLabel3.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        VisionTreePanel.add(xpLabel3, gridBagConstraints);

        modeEnhanceLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        modeEnhanceLabel.setText("?");
        modeEnhanceLabel.setAlignmentY(0.0F);
        modeEnhanceLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Vision Mode Enhancement", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        modeEnhanceLabel.setEnabled(false);
        modeEnhanceLabel.setMaximumSize(new Dimension(200, 38));
        modeEnhanceLabel.setMinimumSize(new Dimension(200, 38));
        modeEnhanceLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        VisionTreePanel.add(modeEnhanceLabel, gridBagConstraints);

        PilotTreeTabbedPane.addTab("Vision", VisionTreePanel);

        SensorTreePanel.setMaximumSize(new Dimension(132, 300));
        SensorTreePanel.setMinimumSize(new Dimension(132, 300));
        SensorTreePanel.setPreferredSize(new Dimension(132, 300));
        SensorTreePanel.setLayout(new GridBagLayout());

        xpLabel4.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel4.setText("10000");
        xpLabel4.setAlignmentY(0.0F);
        xpLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel4.setMaximumSize(new Dimension(50, 38));
        xpLabel4.setMinimumSize(new Dimension(50, 38));
        xpLabel4.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        SensorTreePanel.add(xpLabel4, gridBagConstraints);

        infoGatherLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        infoGatherLabel.setText("Time for target info decreased 25%");
        infoGatherLabel.setAlignmentY(0.0F);
        infoGatherLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Target Info Gathering", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        infoGatherLabel.setMaximumSize(new Dimension(200, 38));
        infoGatherLabel.setMinimumSize(new Dimension(200, 38));
        infoGatherLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        SensorTreePanel.add(infoGatherLabel, gridBagConstraints);

        xpLabel5.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel5.setText("5000");
        xpLabel5.setAlignmentY(0.0F);
        xpLabel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel5.setEnabled(false);
        xpLabel5.setMaximumSize(new Dimension(50, 38));
        xpLabel5.setMinimumSize(new Dimension(50, 38));
        xpLabel5.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        SensorTreePanel.add(xpLabel5, gridBagConstraints);

        hideDamageLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        hideDamageLabel.setText("?");
        hideDamageLabel.setAlignmentY(0.0F);
        hideDamageLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Hide Damage", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        hideDamageLabel.setEnabled(false);
        hideDamageLabel.setMaximumSize(new Dimension(200, 38));
        hideDamageLabel.setMinimumSize(new Dimension(200, 38));
        hideDamageLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        SensorTreePanel.add(hideDamageLabel, gridBagConstraints);

        xpLabel6.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel6.setText("5000");
        xpLabel6.setAlignmentY(0.0F);
        xpLabel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel6.setEnabled(false);
        xpLabel6.setMaximumSize(new Dimension(50, 38));
        xpLabel6.setMinimumSize(new Dimension(50, 38));
        xpLabel6.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        SensorTreePanel.add(xpLabel6, gridBagConstraints);

        signalLossLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        signalLossLabel.setText("?");
        signalLossLabel.setAlignmentY(0.0F);
        signalLossLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Instant Signal Loss", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        signalLossLabel.setEnabled(false);
        signalLossLabel.setMaximumSize(new Dimension(200, 38));
        signalLossLabel.setMinimumSize(new Dimension(200, 38));
        signalLossLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        SensorTreePanel.add(signalLossLabel, gridBagConstraints);

        xpLabel7.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel7.setText("5000");
        xpLabel7.setAlignmentY(0.0F);
        xpLabel7.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel7.setEnabled(false);
        xpLabel7.setMaximumSize(new Dimension(50, 38));
        xpLabel7.setMinimumSize(new Dimension(50, 38));
        xpLabel7.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        SensorTreePanel.add(xpLabel7, gridBagConstraints);

        sensorRangeLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        sensorRangeLabel.setText("Increases sensor range by 15%");
        sensorRangeLabel.setAlignmentY(0.0F);
        sensorRangeLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Sensor Range", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        sensorRangeLabel.setMaximumSize(new Dimension(200, 38));
        sensorRangeLabel.setMinimumSize(new Dimension(200, 38));
        sensorRangeLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        SensorTreePanel.add(sensorRangeLabel, gridBagConstraints);

        xpLabel8.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel8.setText("5000");
        xpLabel8.setAlignmentY(0.0F);
        xpLabel8.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel8.setMaximumSize(new Dimension(50, 38));
        xpLabel8.setMinimumSize(new Dimension(50, 38));
        xpLabel8.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        SensorTreePanel.add(xpLabel8, gridBagConstraints);

        seismicLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        seismicLabel.setText("?");
        seismicLabel.setAlignmentY(0.0F);
        seismicLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Seismic Sensor", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        seismicLabel.setEnabled(false);
        seismicLabel.setMaximumSize(new Dimension(200, 38));
        seismicLabel.setMinimumSize(new Dimension(200, 38));
        seismicLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        SensorTreePanel.add(seismicLabel, gridBagConstraints);

        xpLabel9.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel9.setText("5000");
        xpLabel9.setAlignmentY(0.0F);
        xpLabel9.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel9.setEnabled(false);
        xpLabel9.setMaximumSize(new Dimension(50, 38));
        xpLabel9.setMinimumSize(new Dimension(50, 38));
        xpLabel9.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        SensorTreePanel.add(xpLabel9, gridBagConstraints);

        orbitalScanLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        orbitalScanLabel.setText("?");
        orbitalScanLabel.setAlignmentY(0.0F);
        orbitalScanLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Orbital Scan", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        orbitalScanLabel.setEnabled(false);
        orbitalScanLabel.setMaximumSize(new Dimension(200, 38));
        orbitalScanLabel.setMinimumSize(new Dimension(200, 38));
        orbitalScanLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        SensorTreePanel.add(orbitalScanLabel, gridBagConstraints);

        xpLabel10.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel10.setText("5000");
        xpLabel10.setAlignmentY(0.0F);
        xpLabel10.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel10.setEnabled(false);
        xpLabel10.setMaximumSize(new Dimension(50, 38));
        xpLabel10.setMinimumSize(new Dimension(50, 38));
        xpLabel10.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        SensorTreePanel.add(xpLabel10, gridBagConstraints);

        magnetometerLabel.setFont(new Font("Moire", 0, 10)); // NOI18N
        magnetometerLabel.setText("?");
        magnetometerLabel.setAlignmentY(0.0F);
        magnetometerLabel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Magnetometer", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        magnetometerLabel.setEnabled(false);
        magnetometerLabel.setMaximumSize(new Dimension(200, 38));
        magnetometerLabel.setMinimumSize(new Dimension(200, 38));
        magnetometerLabel.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        SensorTreePanel.add(magnetometerLabel, gridBagConstraints);

        seismicLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        seismicLabel3.setText("?");
        seismicLabel3.setAlignmentY(0.0F);
        seismicLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Seismic Sensor", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        seismicLabel3.setEnabled(false);
        seismicLabel3.setMaximumSize(new Dimension(200, 38));
        seismicLabel3.setMinimumSize(new Dimension(200, 38));
        seismicLabel3.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        SensorTreePanel.add(seismicLabel3, gridBagConstraints);

        xpLabel28.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel28.setText("7500");
        xpLabel28.setAlignmentY(0.0F);
        xpLabel28.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel28.setEnabled(false);
        xpLabel28.setMaximumSize(new Dimension(50, 38));
        xpLabel28.setMinimumSize(new Dimension(50, 38));
        xpLabel28.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        SensorTreePanel.add(xpLabel28, gridBagConstraints);

        sensorRangeLabel4.setFont(new Font("Moire", 0, 10)); // NOI18N
        sensorRangeLabel4.setText("Increases sensor range by 25%");
        sensorRangeLabel4.setAlignmentY(0.0F);
        sensorRangeLabel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Sensor Range", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        sensorRangeLabel4.setMaximumSize(new Dimension(200, 38));
        sensorRangeLabel4.setMinimumSize(new Dimension(200, 38));
        sensorRangeLabel4.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        SensorTreePanel.add(sensorRangeLabel4, gridBagConstraints);

        xpLabel29.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel29.setText("7500");
        xpLabel29.setAlignmentY(0.0F);
        xpLabel29.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel29.setMaximumSize(new Dimension(50, 38));
        xpLabel29.setMinimumSize(new Dimension(50, 38));
        xpLabel29.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        SensorTreePanel.add(xpLabel29, gridBagConstraints);

        PilotTreeTabbedPane.addTab("Sensor", SensorTreePanel);

        SupportTreePanel.setMaximumSize(new Dimension(132, 300));
        SupportTreePanel.setMinimumSize(new Dimension(132, 300));
        SupportTreePanel.setPreferredSize(new Dimension(132, 300));
        SupportTreePanel.setLayout(new GridBagLayout());

        xpLabel11.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel11.setText("15000");
        xpLabel11.setAlignmentY(0.0F);
        xpLabel11.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel11.setMaximumSize(new Dimension(50, 38));
        xpLabel11.setMinimumSize(new Dimension(50, 38));
        xpLabel11.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        SupportTreePanel.add(xpLabel11, gridBagConstraints);

        infoGatherLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        infoGatherLabel1.setText("Capture Rate increased 15%");
        infoGatherLabel1.setAlignmentY(0.0F);
        infoGatherLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Capture Accelerator", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        infoGatherLabel1.setMaximumSize(new Dimension(200, 38));
        infoGatherLabel1.setMinimumSize(new Dimension(200, 38));
        infoGatherLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        SupportTreePanel.add(infoGatherLabel1, gridBagConstraints);

        xpLabel12.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel12.setText("5000");
        xpLabel12.setAlignmentY(0.0F);
        xpLabel12.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel12.setEnabled(false);
        xpLabel12.setMaximumSize(new Dimension(50, 38));
        xpLabel12.setMinimumSize(new Dimension(50, 38));
        xpLabel12.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        SupportTreePanel.add(xpLabel12, gridBagConstraints);

        hideDamageLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        hideDamageLabel1.setText("?");
        hideDamageLabel1.setAlignmentY(0.0F);
        hideDamageLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Friendly Defense", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        hideDamageLabel1.setEnabled(false);
        hideDamageLabel1.setMaximumSize(new Dimension(200, 38));
        hideDamageLabel1.setMinimumSize(new Dimension(200, 38));
        hideDamageLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        SupportTreePanel.add(hideDamageLabel1, gridBagConstraints);

        xpLabel13.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel13.setText("5000");
        xpLabel13.setAlignmentY(0.0F);
        xpLabel13.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel13.setEnabled(false);
        xpLabel13.setMaximumSize(new Dimension(50, 38));
        xpLabel13.setMinimumSize(new Dimension(50, 38));
        xpLabel13.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        SupportTreePanel.add(xpLabel13, gridBagConstraints);

        signalLossLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        signalLossLabel1.setText("?");
        signalLossLabel1.setAlignmentY(0.0F);
        signalLossLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Unit Vision Modes", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        signalLossLabel1.setEnabled(false);
        signalLossLabel1.setMaximumSize(new Dimension(200, 38));
        signalLossLabel1.setMinimumSize(new Dimension(200, 38));
        signalLossLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        SupportTreePanel.add(signalLossLabel1, gridBagConstraints);

        xpLabel14.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel14.setText("5000");
        xpLabel14.setAlignmentY(0.0F);
        xpLabel14.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel14.setEnabled(false);
        xpLabel14.setMaximumSize(new Dimension(50, 38));
        xpLabel14.setMinimumSize(new Dimension(50, 38));
        xpLabel14.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        SupportTreePanel.add(xpLabel14, gridBagConstraints);

        sensorRangeLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        sensorRangeLabel1.setText("?");
        sensorRangeLabel1.setAlignmentY(0.0F);
        sensorRangeLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Artillery Accuracy", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        sensorRangeLabel1.setEnabled(false);
        sensorRangeLabel1.setMaximumSize(new Dimension(200, 38));
        sensorRangeLabel1.setMinimumSize(new Dimension(200, 38));
        sensorRangeLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        SupportTreePanel.add(sensorRangeLabel1, gridBagConstraints);

        xpLabel15.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel15.setText("5000");
        xpLabel15.setAlignmentY(0.0F);
        xpLabel15.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel15.setEnabled(false);
        xpLabel15.setMaximumSize(new Dimension(50, 38));
        xpLabel15.setMinimumSize(new Dimension(50, 38));
        xpLabel15.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        SupportTreePanel.add(xpLabel15, gridBagConstraints);

        seismicLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        seismicLabel1.setText("?");
        seismicLabel1.setAlignmentY(0.0F);
        seismicLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Control Link", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        seismicLabel1.setEnabled(false);
        seismicLabel1.setMaximumSize(new Dimension(200, 38));
        seismicLabel1.setMinimumSize(new Dimension(200, 38));
        seismicLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        SupportTreePanel.add(seismicLabel1, gridBagConstraints);

        xpLabel16.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel16.setText("5000");
        xpLabel16.setAlignmentY(0.0F);
        xpLabel16.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel16.setEnabled(false);
        xpLabel16.setMaximumSize(new Dimension(50, 38));
        xpLabel16.setMinimumSize(new Dimension(50, 38));
        xpLabel16.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        SupportTreePanel.add(xpLabel16, gridBagConstraints);

        orbitalScanLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        orbitalScanLabel1.setText("?");
        orbitalScanLabel1.setAlignmentY(0.0F);
        orbitalScanLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Airstrike Accuracy", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        orbitalScanLabel1.setEnabled(false);
        orbitalScanLabel1.setMaximumSize(new Dimension(200, 38));
        orbitalScanLabel1.setMinimumSize(new Dimension(200, 38));
        orbitalScanLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        SupportTreePanel.add(orbitalScanLabel1, gridBagConstraints);

        xpLabel17.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel17.setText("5000");
        xpLabel17.setAlignmentY(0.0F);
        xpLabel17.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel17.setEnabled(false);
        xpLabel17.setMaximumSize(new Dimension(50, 38));
        xpLabel17.setMinimumSize(new Dimension(50, 38));
        xpLabel17.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        SupportTreePanel.add(xpLabel17, gridBagConstraints);

        magnetometerLabel1.setFont(new Font("Moire", 0, 10)); // NOI18N
        magnetometerLabel1.setText("?");
        magnetometerLabel1.setAlignmentY(0.0F);
        magnetometerLabel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Drone", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        magnetometerLabel1.setEnabled(false);
        magnetometerLabel1.setMaximumSize(new Dimension(200, 38));
        magnetometerLabel1.setMinimumSize(new Dimension(200, 38));
        magnetometerLabel1.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        SupportTreePanel.add(magnetometerLabel1, gridBagConstraints);

        magnetometerLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        magnetometerLabel3.setText("?");
        magnetometerLabel3.setAlignmentY(0.0F);
        magnetometerLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Drone", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        magnetometerLabel3.setEnabled(false);
        magnetometerLabel3.setMaximumSize(new Dimension(200, 38));
        magnetometerLabel3.setMinimumSize(new Dimension(200, 38));
        magnetometerLabel3.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        SupportTreePanel.add(magnetometerLabel3, gridBagConstraints);

        xpLabel27.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel27.setText("7500");
        xpLabel27.setAlignmentY(0.0F);
        xpLabel27.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel27.setEnabled(false);
        xpLabel27.setMaximumSize(new Dimension(50, 38));
        xpLabel27.setMinimumSize(new Dimension(50, 38));
        xpLabel27.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        SupportTreePanel.add(xpLabel27, gridBagConstraints);

        PilotTreeTabbedPane.addTab("Support", SupportTreePanel);

        TargetingTreePanel.setMaximumSize(new Dimension(132, 300));
        TargetingTreePanel.setMinimumSize(new Dimension(132, 300));
        TargetingTreePanel.setPreferredSize(new Dimension(132, 300));
        TargetingTreePanel.setLayout(new GridBagLayout());

        xpLabel18.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel18.setText("5000");
        xpLabel18.setAlignmentY(0.0F);
        xpLabel18.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel18.setEnabled(false);
        xpLabel18.setMaximumSize(new Dimension(50, 38));
        xpLabel18.setMinimumSize(new Dimension(50, 38));
        xpLabel18.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        TargetingTreePanel.add(xpLabel18, gridBagConstraints);

        infoGatherLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        infoGatherLabel2.setText("?");
        infoGatherLabel2.setAlignmentY(0.0F);
        infoGatherLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Multi Target", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        infoGatherLabel2.setEnabled(false);
        infoGatherLabel2.setMaximumSize(new Dimension(200, 38));
        infoGatherLabel2.setMinimumSize(new Dimension(200, 38));
        infoGatherLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        TargetingTreePanel.add(infoGatherLabel2, gridBagConstraints);

        xpLabel19.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel19.setText("5000");
        xpLabel19.setAlignmentY(0.0F);
        xpLabel19.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel19.setEnabled(false);
        xpLabel19.setMaximumSize(new Dimension(50, 38));
        xpLabel19.setMinimumSize(new Dimension(50, 38));
        xpLabel19.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        TargetingTreePanel.add(xpLabel19, gridBagConstraints);

        hideDamageLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        hideDamageLabel2.setText("?");
        hideDamageLabel2.setAlignmentY(0.0F);
        hideDamageLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Targeting Delay", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        hideDamageLabel2.setEnabled(false);
        hideDamageLabel2.setMaximumSize(new Dimension(200, 38));
        hideDamageLabel2.setMinimumSize(new Dimension(200, 38));
        hideDamageLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        TargetingTreePanel.add(hideDamageLabel2, gridBagConstraints);

        xpLabel20.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel20.setText("5000");
        xpLabel20.setAlignmentY(0.0F);
        xpLabel20.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel20.setEnabled(false);
        xpLabel20.setMaximumSize(new Dimension(50, 38));
        xpLabel20.setMinimumSize(new Dimension(50, 38));
        xpLabel20.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        TargetingTreePanel.add(xpLabel20, gridBagConstraints);

        signalLossLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        signalLossLabel2.setText("?");
        signalLossLabel2.setAlignmentY(0.0F);
        signalLossLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Disrupt HUD", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        signalLossLabel2.setEnabled(false);
        signalLossLabel2.setMaximumSize(new Dimension(200, 38));
        signalLossLabel2.setMinimumSize(new Dimension(200, 38));
        signalLossLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        TargetingTreePanel.add(signalLossLabel2, gridBagConstraints);

        xpLabel21.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel21.setText("5000");
        xpLabel21.setAlignmentY(0.0F);
        xpLabel21.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel21.setEnabled(false);
        xpLabel21.setMaximumSize(new Dimension(50, 38));
        xpLabel21.setMinimumSize(new Dimension(50, 38));
        xpLabel21.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        TargetingTreePanel.add(xpLabel21, gridBagConstraints);

        sensorRangeLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        sensorRangeLabel2.setText("Increases Decay Time to 2.75 sec");
        sensorRangeLabel2.setAlignmentY(0.0F);
        sensorRangeLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Target Decay", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        sensorRangeLabel2.setMaximumSize(new Dimension(200, 38));
        sensorRangeLabel2.setMinimumSize(new Dimension(200, 38));
        sensorRangeLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        TargetingTreePanel.add(sensorRangeLabel2, gridBagConstraints);

        xpLabel22.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel22.setText("5000");
        xpLabel22.setAlignmentY(0.0F);
        xpLabel22.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel22.setMaximumSize(new Dimension(50, 38));
        xpLabel22.setMinimumSize(new Dimension(50, 38));
        xpLabel22.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        TargetingTreePanel.add(xpLabel22, gridBagConstraints);

        seismicLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        seismicLabel2.setText("Target stays on radar within 200m");
        seismicLabel2.setAlignmentY(0.0F);
        seismicLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "360 Radar", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        seismicLabel2.setMaximumSize(new Dimension(200, 38));
        seismicLabel2.setMinimumSize(new Dimension(200, 38));
        seismicLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        TargetingTreePanel.add(seismicLabel2, gridBagConstraints);

        xpLabel23.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel23.setText("15000");
        xpLabel23.setAlignmentY(0.0F);
        xpLabel23.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel23.setMaximumSize(new Dimension(50, 38));
        xpLabel23.setMinimumSize(new Dimension(50, 38));
        xpLabel23.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        TargetingTreePanel.add(xpLabel23, gridBagConstraints);

        orbitalScanLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        orbitalScanLabel2.setText("?");
        orbitalScanLabel2.setAlignmentY(0.0F);
        orbitalScanLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Disable Comms", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        orbitalScanLabel2.setEnabled(false);
        orbitalScanLabel2.setMaximumSize(new Dimension(200, 38));
        orbitalScanLabel2.setMinimumSize(new Dimension(200, 38));
        orbitalScanLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        TargetingTreePanel.add(orbitalScanLabel2, gridBagConstraints);

        xpLabel24.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel24.setText("5000");
        xpLabel24.setAlignmentY(0.0F);
        xpLabel24.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel24.setEnabled(false);
        xpLabel24.setMaximumSize(new Dimension(50, 38));
        xpLabel24.setMinimumSize(new Dimension(50, 38));
        xpLabel24.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        TargetingTreePanel.add(xpLabel24, gridBagConstraints);

        magnetometerLabel2.setFont(new Font("Moire", 0, 10)); // NOI18N
        magnetometerLabel2.setText("?");
        magnetometerLabel2.setAlignmentY(0.0F);
        magnetometerLabel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Control Link", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        magnetometerLabel2.setEnabled(false);
        magnetometerLabel2.setMaximumSize(new Dimension(200, 38));
        magnetometerLabel2.setMinimumSize(new Dimension(200, 38));
        magnetometerLabel2.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        TargetingTreePanel.add(magnetometerLabel2, gridBagConstraints);

        xpLabel25.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel25.setText("7500");
        xpLabel25.setAlignmentY(0.0F);
        xpLabel25.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel25.setEnabled(false);
        xpLabel25.setMaximumSize(new Dimension(50, 38));
        xpLabel25.setMinimumSize(new Dimension(50, 38));
        xpLabel25.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        TargetingTreePanel.add(xpLabel25, gridBagConstraints);

        infoGatherLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        infoGatherLabel3.setText("?");
        infoGatherLabel3.setAlignmentY(0.0F);
        infoGatherLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Multi Target", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        infoGatherLabel3.setEnabled(false);
        infoGatherLabel3.setMaximumSize(new Dimension(200, 38));
        infoGatherLabel3.setMinimumSize(new Dimension(200, 38));
        infoGatherLabel3.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        TargetingTreePanel.add(infoGatherLabel3, gridBagConstraints);

        sensorRangeLabel3.setFont(new Font("Moire", 0, 10)); // NOI18N
        sensorRangeLabel3.setText("Increases Decay Time to 3.5 sec");
        sensorRangeLabel3.setAlignmentY(0.0F);
        sensorRangeLabel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Advanced Target Decay", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        sensorRangeLabel3.setMaximumSize(new Dimension(200, 38));
        sensorRangeLabel3.setMinimumSize(new Dimension(200, 38));
        sensorRangeLabel3.setPreferredSize(new Dimension(200, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        TargetingTreePanel.add(sensorRangeLabel3, gridBagConstraints);

        xpLabel26.setFont(new Font("Moire", 0, 10)); // NOI18N
        xpLabel26.setText("7500");
        xpLabel26.setAlignmentY(0.0F);
        xpLabel26.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "XP", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Moire", 0, 11))); // NOI18N
        xpLabel26.setMaximumSize(new Dimension(50, 38));
        xpLabel26.setMinimumSize(new Dimension(50, 38));
        xpLabel26.setPreferredSize(new Dimension(50, 38));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        TargetingTreePanel.add(xpLabel26, gridBagConstraints);

        PilotTreeTabbedPane.addTab("Targeting", TargetingTreePanel);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(PilotTreeTabbedPane, gridBagConstraints);

        ButtonPanel.setMaximumSize(new Dimension(132, 300));
        ButtonPanel.setMinimumSize(new Dimension(132, 300));
        ButtonPanel.setPreferredSize(new Dimension(132, 300));
        ButtonPanel.setLayout(new GridBagLayout());

        closeButton.setFont(new Font("Moire", 0, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.setMaximumSize(new Dimension(120, 30));
        closeButton.setMinimumSize(new Dimension(120, 30));
        closeButton.setPreferredSize(new Dimension(120, 30));
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ButtonPanel.add(closeButton, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(ButtonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel ButtonPanel;
    private JTabbedPane PilotTreeTabbedPane;
    private JPanel SensorTreePanel;
    private JPanel SupportTreePanel;
    private JPanel TargetingTreePanel;
    private JPanel VisionTreePanel;
    private JLabel advZoomLabel;
    JButton closeButton;
    private JLabel hideDamageLabel;
    private JLabel hideDamageLabel1;
    private JLabel hideDamageLabel2;
    private JLabel infoGatherLabel;
    private JLabel infoGatherLabel1;
    private JLabel infoGatherLabel2;
    private JLabel infoGatherLabel3;
    private JLabel magnetometerLabel;
    private JLabel magnetometerLabel1;
    private JLabel magnetometerLabel2;
    private JLabel magnetometerLabel3;
    private JLabel modeEnhanceLabel;
    private JLabel orbitalScanLabel;
    private JLabel orbitalScanLabel1;
    private JLabel orbitalScanLabel2;
    private JLabel seismicLabel;
    private JLabel seismicLabel1;
    private JLabel seismicLabel2;
    private JLabel seismicLabel3;
    private JLabel sensorRangeLabel;
    private JLabel sensorRangeLabel1;
    private JLabel sensorRangeLabel2;
    private JLabel sensorRangeLabel3;
    private JLabel sensorRangeLabel4;
    private JLabel signalLossLabel;
    private JLabel signalLossLabel1;
    private JLabel signalLossLabel2;
    private JLabel xpLabel1;
    private JLabel xpLabel10;
    private JLabel xpLabel11;
    private JLabel xpLabel12;
    private JLabel xpLabel13;
    private JLabel xpLabel14;
    private JLabel xpLabel15;
    private JLabel xpLabel16;
    private JLabel xpLabel17;
    private JLabel xpLabel18;
    private JLabel xpLabel19;
    private JLabel xpLabel2;
    private JLabel xpLabel20;
    private JLabel xpLabel21;
    private JLabel xpLabel22;
    private JLabel xpLabel23;
    private JLabel xpLabel24;
    private JLabel xpLabel25;
    private JLabel xpLabel26;
    private JLabel xpLabel27;
    private JLabel xpLabel28;
    private JLabel xpLabel29;
    private JLabel xpLabel3;
    private JLabel xpLabel4;
    private JLabel xpLabel5;
    private JLabel xpLabel6;
    private JLabel xpLabel7;
    private JLabel xpLabel8;
    private JLabel xpLabel9;
    private JLabel zoomDisruptorLabel;
    // End of variables declaration//GEN-END:variables
}
